In [1]:
import pandas as pd

In [2]:
feeders = pd.read_csv("../data/feeders.csv")
meters = pd.read_csv("../data/meters.csv")
outages = pd.read_csv("../data/outages.csv")

In [3]:
feeders

,feeder_id,substation,town,voltage_kv,customers_served,commissioned_year,latitude,longitude
0,FD-001,Bamenda Main,Bamenda,30,8723,1985.0,5.96021,10.16141
1,FD-002,Bamenda Main,Bamenda,15,6103,1985.0,5.95957,10.14537
2,FD-003,Bamenda Main,Bamenda,NaN,7637,2019.0,5.96261,10.11069
3,FD-004,Nkwen,Bamenda,NaN,3149,2019.0,5.97457,10.14588
4,FD-005,Nkwen,Bamenda,30,7505,1985.0,6.02148,10.18291
5,FD-006,Mankon,Bamenda,30,7537,1985.0,5.95909,10.10838
6,FD-007,Mankon,Bamenda,30,1908,2009.0,5.96298,10.15734
7,FD-008,Mankon,Bamenda,30kV,6607,1998.0,5.97171,10.13234
8,FD-009,Mankon,Bamenda,33,5909,1978.0,5.95671,10.13663
9,FD-010,Bafut,Bafut,15,421,2014.0,6.11700,10.13130
10,FD-011,Bafut,Bafut,15,7843,NaN,6.06413,10.08947
11,FD-012,Bafut,Bafut,NaN,1616,NaN,6.10025,10.09759
12,FD-013,Bali,Bali,33,8801,2014.0,5.87102,10.03345
13,FD-014,Bali,Bali,30,6379,1992.0,5.88578,10.05373
14,FD-015,Bali,Bali,NaN,1376,2004.0,5.89666,10.02107
15,FD-016,Santa,Santa,33,2651,2019.0,5.81294,10.23152
16,FD-017,Santa,Santa,30kV,2948,NaN,5.81553,10.18174
17,FD-018,Santa,Santa,30,4734,2019.0,5.81764,10.18719
18,FD-019,Ndop,Ndop,NaN,4066,1998.0,5.96008,10.44812
19,FD-020,Ndop,Ndop,15,4879,2019.0,5.97999,10.47763
20,FD-021,Ndop,Ndop,NaN,3225,2009.0,5.98039,10.42040
21,FD-022,Ndop,Ndop,NaN,953,1992.0,5.97303,10.41656
22,FD-023,Kumbo,Kumbo,15,2814,NaN,6.17975,10.64770
23,FD-024,Kumbo,Kumbo,NaN,3423,2019.0,6.22260,10.65005
24,FD-025,Kumbo,Kumbo,30kV,5210,1985.0,6.21059,10.64215
25,FD-026,Wum,Wum,30kV,3795,1978.0,6.39978,10.06622
26,FD-027,Wum,Wum,30kV,2548,1985.0,6.37787,10.05152
27,FD-028,Wum,Wum,30,6431,1985.0,6.40935,10.06738
28,FD-029,Wum,Wum,30kV,2937,2014.0,6.38871,10.04671
29,FD-030,Fundong,Fundong,15,8068,2014.0,6.25306,10.30449
30,FD-031,Fundong,Fundong,33,1876,2014.0,6.25346,10.26216
31,FD-032,Fundong,Fundong,15,2351,2009.0,6.24561,10.25013
32,FD-033,Mbengwi,Mbengwi,15,1464,2014.0,5.97679,10.00766
33,FD-034,Mbengwi,Mbengwi,30,1620,1985.0,6.00523,10.02378
34,FD-035,Batibo,Batibo,NaN,1512,1978.0,5.80107,9.85587
35,FD-036,Batibo,Batibo,30,4039,1998.0,5.84332,9.85139
36,FD-037,Batibo,Batibo,NaN,3662,1985.0,5.83648,9.85903

In [4]:
feeders['voltage_kv'] = (
  feeders["voltage_kv"].astype("string").str.replace("kV", "",regex = False)
)

feeders["voltage_kv"] = pd.to_numeric(
  feeders["voltage_kv"],
     errors="coerce"
)

In [5]:
feeders["voltage_kv"].unique()

<IntegerArray>
[30, 15, <NA>, 33]
Length: 4, dtype: Int64

In [6]:
feeders[feeders["voltage_kv"].isna()]

,feeder_id,substation,town,voltage_kv,customers_served,commissioned_year,latitude,longitude
2,FD-003,Bamenda Main,Bamenda,<NA>,7637,2019.0,5.96261,10.11069
3,FD-004,Nkwen,Bamenda,<NA>,3149,2019.0,5.97457,10.14588
11,FD-012,Bafut,Bafut,<NA>,1616,NaN,6.10025,10.09759
14,FD-015,Bali,Bali,<NA>,1376,2004.0,5.89666,10.02107
18,FD-019,Ndop,Ndop,<NA>,4066,1998.0,5.96008,10.44812
20,FD-021,Ndop,Ndop,<NA>,3225,2009.0,5.98039,10.42040
21,FD-022,Ndop,Ndop,<NA>,953,1992.0,5.97303,10.41656
23,FD-024,Kumbo,Kumbo,<NA>,3423,2019.0,6.22260,10.65005
34,FD-035,Batibo,Batibo,<NA>,1512,1978.0,5.80107,9.85587
36,FD-037,Batibo,Batibo,<NA>,3662,1985.0,5.83648,9.85903

In [7]:
feeders["customers_served"].info()

<class 'pandas.Series'>
RangeIndex: 37 entries, 0 to 36
Series name: customers_served
Non-Null Count  Dtype
--------------  -----
37 non-null     int64
dtypes: int64(1)
memory usage: 428.0 bytes

In [8]:
feeders.isnull().sum()

feeder_id             0
substation            0
town                  0
voltage_kv           10
customers_served      0
commissioned_year     4
latitude              0
longitude             0
dtype: int64

In [9]:
feeders[feeders["voltage_kv"].isna()][
    ["feeder_id", "substation", "town", "voltage_kv"]
]

   feeder_id    substation     town  voltage_kv
2     FD-003  Bamenda Main  Bamenda        <NA>
3     FD-004         Nkwen  Bamenda        <NA>
11    FD-012         Bafut    Bafut        <NA>
14    FD-015          Bali     Bali        <NA>
18    FD-019          Ndop     Ndop        <NA>
20    FD-021          Ndop     Ndop        <NA>
21    FD-022          Ndop     Ndop        <NA>
23    FD-024         Kumbo    Kumbo        <NA>
34    FD-035        Batibo   Batibo        <NA>
36    FD-037        Batibo   Batibo        <NA>

In [10]:
feeders[feeders["commissioned_year"].isna()][
    ["feeder_id", "substation", "town", "commissioned_year"]
]

   feeder_id substation   town  commissioned_year
10    FD-011      Bafut  Bafut                NaN
11    FD-012      Bafut  Bafut                NaN
16    FD-017      Santa  Santa                NaN
22    FD-023      Kumbo  Kumbo                NaN

In [11]:
meters.head(60)

,meter_id,feeder_id,customer_type,installed_on,tariff_band,monthly_kwh_avg,prepaid
0,MT305729,FD-016,public,26/08/2023,industrial,NaN,0
1,MT307480,FD-026,public,2025-07-09,commercial,NaN,True
2,MT308834,FD-028,residential,07/02/2020,commercial,127.2,FALSE
3,MT309716,FD-002,industrial,2021-08-27,commercial,131.6 kWh,True
4,MT305213,FD-006,residential,2024-02-19,commercial,170.5,True
5,MT303726,FD-035,industrial,2020-10-26,industrial,102.9 kWh,False
6,MT304157,FD-022,industrial,2024-12-04,domestic-low,63.6 kWh,1
7,MT305489,FD-008,public,2022-10-29,social,188.4 kWh,TRUE
8,MT308478,FD-021,residential,2022-07-29,industrial,NaN,False
9,MT307745,FD-033,residential,2023-08-13,domestic-low,NaN,False
10,MT302039,FD-032,residential,2020-06-18,domestic-low,198.9 kWh,0
11,MT308963,FD-014,public,2020-03-17,social,117.3 kWh,no
12,MT306035,FD-003,commercial,2019-12-14,social,NaN,1
13,MT308345,FD-034,residential,2020-10-14,social,NaN,FALSE
14,MT307802,FD-016,residential,2019-06-30,domestic-low,8.1 kWh,False
15,MT300701,FD-002,residential,2020-09-02,social,NaN,FALSE
16,MT309053,FD-020,industrial,2019-03-01,domestic-low,51.7 kWh,TRUE
17,MT310280,FD-023,public,2019-03-31,domestic-low,67.5,True
18,MT305856,FD-003,residential,2023-09-01,domestic-low,119.9 kWh,0
19,MT304582,FD-010,industrial,2020-07-13,domestic-standard,98.1,False
20,MT305442,FD-008,residential,2025-10-07,social,NaN,no
21,MT301067,FD-001,industrial,2020-02-27,social,24.0,no
22,MT303859,FD-005,industrial,2025-10-14,industrial,73.7,no
23,MT309344,FD-027,residential,2024-02-10,domestic-standard,131.2,FALSE
24,MT310018,FD-029,industrial,2026-04-28,social,NaN,yes
25,MT304777,FD-004,residential,03/06/2020,commercial,75.2 kWh,0
26,MT310495,FD-008,residential,2020-07-05,domestic-low,NaN,False
27,MT310086,FD-001,commercial,2023-03-12,commercial,105.6 kWh,TRUE
28,MT306917,FD-012,residential,2024-12-30,domestic-standard,101.9 kWh,no
29,MT300743,FD-030,residential,08/10/2025,domestic-low,NaN,True
30,MT307103,FD-015,industrial,2021-12-11,domestic-low,NaN,TRUE
31,MT308022,FD-010,residential,2022-03-17,industrial,64.2 kWh,0
32,MT304298,FD-029,industrial,2023-11-27,commercial,145.9,1
33,MT307244,FD-019,residential,2019-01-24,commercial,103.7 kWh,1
34,MT304948,FD-017,residential,2025-07-09,social,60.5,FALSE
35,MT300253,FD-008,residential,02/10/2023,commercial,308.7,True
36,MT308944,FD-035,commercial,2024-02-24,domestic-low,114.2 kWh,0
37,MT301085,FD-033,residential,2023-07-01,domestic-low,166.7,no
38,MT304167,FD-001,industrial,2019-11-04,industrial,83.3 kWh,False
39,MT310618,FD-037,industrial,2022-07-03,domestic-low,NaN,no
40,MT305692,FD-002,residential,2025-08-20,industrial,NaN,yes
41,MT307578,FD-022,residential,2023-04-20,domestic-standard,NaN,FALSE
42,MT304268,FD-006,commercial,2022-08-30,social,95.5,FALSE
43,MT308542,FD-001,residential,12/03/2023,commercial,NaN,FALSE
44,MT310194,FD-025,residential,2022-06-02,domestic-low,NaN,FALSE
45,MT307754,FD-001,commercial,2026-05-21,domestic-low,145.7 kWh,FALSE
46,MT301368,FD-031,public,2020-07-22,social,89.1,FALSE
47,MT307195,FD-035,residential,2020-11-03,commercial,158.9,TRUE
48,MT301040,FD-032,commercial,2026-05-20,domestic-low,NaN,yes
49,MT306629,FD-018,residential,2026-01-10,domestic-low,NaN,yes
50,MT308867,FD-014,residential,2020-06-08,industrial,43.0 kWh,1
51,MT310289,FD-010,residential,2023-08-08,industrial,13.0,TRUE
52,MT302425,FD-016,industrial,2020-12-18,domestic-low,NaN,False
53,MT307748,FD-010,residential,2024-09-09,domestic-standard,51.9 kWh,TRUE
54,MT306088,FD-011,public,2021-12-20,domestic-low,85.6,False
55,MT309156,FD-037,public,16/05/2022,domestic-low,NaN,True
56,MT306251,FD-029,industrial,2019-01-12,domestic-low,10.4 kWh,1
57,MT300690,FD-004,public,2020-10-26,domestic-low,119.3 kWh,yes
58,MT308777,FD-026,residential,2025-03-16,domestic-standard,74.4,False
59,MT308262,FD-030,residential,2023-01-31,domestic-low,103.3,yes

In [12]:
meters.info()

<class 'pandas.DataFrame'>
RangeIndex: 11090 entries, 0 to 11089
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   meter_id         11090 non-null  str
 1   feeder_id        11090 non-null  str
 2   customer_type    11090 non-null  str
 3   installed_on     11090 non-null  str
 4   tariff_band      11090 non-null  str
 5   monthly_kwh_avg  7363 non-null   str
 6   prepaid          11090 non-null  str
dtypes: str(7)
memory usage: 606.6 KB

In [13]:
meters["installed_on"] = pd.to_datetime(
    meters["installed_on"],
    dayfirst=True,
    errors="coerce"
)

In [14]:
meters["prepaid"] = meters["prepaid"].replace({
    1: True,
    0: False,
    "1": True,
    "0": False,
    "True": True,
    "TRUE": True,
    "False": False,
    "FALSE": False,
    "yes": True,
    "Yes": True,
    "YES": True,
    "no": False,
    "No": False,
    "NO": False
})

In [15]:
meters["monthly_kwh_avg"] = (
    meters["monthly_kwh_avg"]
    .astype("string")
    .str.replace(" kWh", "", regex=False)
)

meters["monthly_kwh_avg"] = pd.to_numeric(
    meters["monthly_kwh_avg"],
    errors="coerce"
)

In [16]:
meters["monthly_kwh_avg"].unique()

<FloatingArray>
[ <NA>, 127.2, 131.6, 170.5, 102.9,  63.6, 188.4, 198.9, 117.3,   8.1,
 ...
 210.8, 182.9,  78.1, 268.6, 103.0, 189.6, 238.6, 219.3, 276.8, 199.7]
Length: 2249, dtype: Float64

In [17]:
meters.isnull().sum()

meter_id              0
feeder_id             0
customer_type         0
installed_on       9944
tariff_band           0
monthly_kwh_avg    3727
prepaid               0
dtype: int64

In [18]:
meters["meter_id"].duplicated().sum()

np.int64(90)

In [19]:
meters[meters["meter_id"].duplicated(keep=False)]

,meter_id,feeder_id,customer_type,installed_on,tariff_band,monthly_kwh_avg,prepaid
53,MT307748,FD-010,residential,NaT,domestic-standard,51.9,True
146,MT310679,FD-002,public,NaT,domestic-low,64.7,True
166,MT302323,FD-001,industrial,NaT,industrial,<NA>,True
240,MT300875,FD-036,residential,NaT,domestic-low,<NA>,False
265,MT309581,FD-028,public,NaT,commercial,122.4,True
...,...,...,...,...,...,...,...
10646,MT302998,FD-024,residential,NaT,domestic-low,<NA>,True
10690,MT310785,FD-004,industrial,NaT,industrial,<NA>,True
10860,MT301261,FD-015,industrial,2024-06-17,domestic-low,91.7,True
10871,MT310507,FD-023,residential,NaT,domestic-low,70.5,False
11065,MT309228,FD-024,industrial,NaT,commercial,<NA>,False

In [20]:
meters_raw = pd.read_csv("../data/meters.csv")

In [21]:
meters_raw.loc[
    pd.to_datetime(
        meters_raw["installed_on"],
        dayfirst=True,
        errors="coerce"
    ).isna(),
    "installed_on"
].unique()

<StringArray>
['2025-07-09', '2021-08-27', '2024-02-19', '2020-10-26', '2024-12-04',
 '2022-10-29', '2022-07-29', '2023-08-13', '2020-06-18', '2020-03-17',
 ...
 '2022-11-25', '2025-10-06', '2024-05-16', '2019-08-03', '2025-08-02',
 '2024-03-02', '2021-04-26', '2021-01-18', '2019-09-11', '2025-06-10']
Length: 2628, dtype: str

In [22]:
dates = meters["installed_on"].astype("string")

slash_dates = dates.str.contains("/", na=False)

meters.loc[slash_dates, "installed_on"] = pd.to_datetime(
    dates[slash_dates],
    format="%d/%m/%Y",
    errors="coerce"
)

meters.loc[~slash_dates, "installed_on"] = pd.to_datetime(
    dates[~slash_dates],
    format="%Y-%m-%d",
    errors="coerce"
)

In [23]:
meters["installed_on"].isna().sum()

np.int64(9944)

In [24]:
print(meters["installed_on"].head(10))

0   2023-08-26
1          NaT
2   2020-02-07
3          NaT
4          NaT
5          NaT
6          NaT
7          NaT
8          NaT
9          NaT
Name: installed_on, dtype: datetime64[us]

In [25]:
print(meters["installed_on"].dtype)

datetime64[us]

In [26]:
print(meters["installed_on"].isna().sum())

9944

In [27]:
outages.info()

<class 'pandas.DataFrame'>
RangeIndex: 3021 entries, 0 to 3020
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   outage_id           3021 non-null   str
 1   feeder_id           3021 non-null   str
 2   start_ts            3021 non-null   str
 3   end_ts              3021 non-null   str
 4   duration_min        3021 non-null   str
 5   cause               3021 non-null   str
 6   crew_id             2872 non-null   str
 7   customers_affected  3021 non-null   int64
dtypes: int64(1), str(7)
memory usage: 188.9 KB

In [28]:
outages.head(60)

,outage_id,feeder_id,start_ts,end_ts,duration_min,cause,crew_id,customers_affected
0,OG-001652,FD-024,2025-08-10 19:15:00,2025-08-10 20:59:00,104,lightning strike,CR-13,1270
1,OG-000355,FD-005,2024-06-05 19:45:00,2024-06-05 21:48:00,123,lightning strike,CR-07,3255
2,OG-002224,FD-020,31/03/2026 05:30,2026-03-31 07:49:00,139,storm damage,CR-14,2227
3,OG-001615,FD-036,2025-08-04 17:30:00,04/08/2025 20:19,169,storm damage,CR-18,2710
4,OG-000587,FD-010,2024-08-01 15:15:00,2024-08-01 16:51:00,96,storm damage,CR-03,61
5,OG-001511,FD-030,2025-07-10 14:15:00,2025-07-10 16:45:00,150,storm damage,CR-10,7841
6,OG-001222,FD-014,2025-04-14 12:15:00,2025-04-14 16:09:00,234,vegetation contact,NaN,5116
7,OG-002047,FD-002,2025-11-25 12:15:00,2025-11-25 16:33:00,258,storm damage,CR-04,364
8,OG-002054,FD-033,04/12/2025 23:15,2025-12-05 01:41:00,146,pole collapse,CR-11,785
9,OG-000120,FD-021,2024-03-22 20:30:00,2024-03-22 22:21:00,111,pole collapse,CR-15,2169
10,OG-900288,FD-9288,12/04/2024 10:00,2025-03-20 13:00:00,180,unknown,CR-01,500
11,OG-001439,FD-032,1750504500,2025-06-21 13:00:00,105,pole collapse,CR-07,295
12,OG-000071,FD-036,2024-03-01 00:45:00,2024-03-01 07:28:00,403,storm damage,CR-17,1594
13,OG-000908,FD-033,2024-10-03 13:45:00,2024-10-03 15:30:00,105,overload,CR-04,1437
14,OG-000217,FD-009,26/04/2024 15:30,2024-04-26 18:29:00,179,lightning strike,CR-14,2954
15,OG-001724,FD-001,24/08/2025 02:30,2025-08-24 02:38:00,8,pole collapse,CR-18,4511
16,OG-002075,FD-015,2025-12-19 06:30:00,2025-12-19 08:35:00,125,transformer fault,CR-05,485
17,OG-002379,FD-017,2026-05-18 17:30:00,2026-05-18 19:50:00,140,vegetation contact,CR-04,2012
18,OG-001129,FD-036,06/03/2025 20:30,2025-03-07 00:29:00,239,vegetation contact,CR-01,1827
19,OG-002256,FD-033,09/04/2026 10:00,2026-04-09 12:10:00,130,transformer fault,CR-13,426
20,OG-001899,FD-001,2025-10-01 09:15:00,01/10/2025 10:00,45,storm damage,CR-06,992
21,OG-000197,FD-015,2024-04-18 08:00:00,2024-04-18 14:05:00,365,storm damage,CR-05,559
22,OG-000040,FD-017,2024-01-27 01:15:00,2024-01-27 02:10:00,55,planned maintenance,CR-15,1779
23,OG-002071,FD-021,2025-12-13 21:45:00,2025-12-13 23:51:00,126,lightning strike,CR-02,1621
24,OG-900333,FD-9333,2025-04-03 10:00:00,1744722000,180,unknown,CR-01,500
25,OG-000199,FD-023,2024-04-19 14:30:00,2024-04-19 16:43:00,133,pole collapse,CR-12,2205
26,OG-000637,FD-032,2024-08-11 15:30:00,2024-08-11 19:16:00,226,vegetation contact,CR-10,1754
27,OG-000917,FD-034,2024-10-05 16:30:00,2024-10-05 19:35:00,185,vegetation contact,CR-08,451
28,OG-001168,FD-034,23/03/2025 09:00,2025-03-23 09:08:00,8,planned maintenance,CR-04,293
29,OG-000707,FD-029,2024-08-24 13:15:00,2024-08-24 16:22:00,187,unknown,CR-12,1506
30,OG-002411,FD-021,2026-05-25 09:00:00,25/05/2026 12:39,219,storm damage,CR-14,2396
31,OG-001668,FD-022,2025-08-13 17:45:00,1755112920,97,pole collapse,CR-13,441
32,OG-001232,FD-029,2025-04-17 14:45:00,2025-04-17 18:07:00,202,lightning strike,CR-13,2442
33,OG-001477,FD-012,02/07/2025 02:00,2025-07-02 03:33:00,93,equipment failure,CR-05,257
34,OG-001617,FD-037,2025-08-04 01:00:00,2025-08-04 02:06:00,66,storm damage,CR-03,1552
35,OG-000326,FD-012,2024-05-28 21:15:00,1716934020,52,overload,CR-10,1374
36,OG-000370,FD-002,09/06/2024 13:00,1717946820,147,vegetation contact,CR-10,4170
37,OG-000398,FD-026,1718656200,2024-06-17 23:38:00,188,vegetation contact,CR-14,3131
38,OG-002276,FD-006,2026-04-15 10:00:00,2026-04-15 11:24:00,84,vegetation contact,CR-12,3952
39,OG-001712,FD-009,2025-08-22 16:30:00,2025-08-22 23:13:00,403,lightning strike,CR-06,2838
40,OG-001333,FD-028,2025-05-19 12:30:00,2025-05-19 14:56:00,146,vegetation contact,CR-04,5565
41,OG-002365,FD-027,1778555700,12/05/2026 05:05,110,planned maintenance,CR-13,950
42,OG-002129,FD-022,2026-02-16 11:00:00,2026-02-16 11:23:00,23,planned maintenance,CR-02,912
43,OG-000021,FD-015,2024-01-15 09:45:00,2024-01-15 13:02:00,197,planned maintenance,CR-05,969
44,OG-000439,FD-007,27/06/2024 12:30,2024-06-27 13:57:00,87,overload,CR-17,1146
45,OG-000409,FD-014,2024-06-20 09:30:00,2024-06-20 13:49:00,259,STORM DAMAGE,CR-17,3396
46,OG-000986,FD-021,1730073600,2024-10-28 03:51:00,231,storm damage,CR-12,169
47,OG-000605,FD-036,2024-08-05 23:00:00,2024-08-06 02:13:00,193,unknown,NaN,3524
48,OG-001171,FD-023,2025-03-25 09:45:00,2025-03-25 13:09:00,204,equipment failure,CR-14,2156
49,OG-900313,FD-9313,2025-03-03 10:00:00,28/01/2025 13:00,180,unknown,CR-01,500
50,OG-000480,FD-004,2024-07-06 21:45:00,1720308000,95,planned maintenance,CR-08,2935
51,OG-001525,FD-034,2025-07-13 05:30:00,2025-07-13 08:21:00,171,lightning strike,CR-08,761
52,OG-002234,FD-027,2026-04-02 05:30:00,2026-04-02 08:08:00,158,planned maintenance,CR-08,1091
53,OG-001547,FD-002,2025-07-17 03:45:00,1752728880,83,cable theft,CR-11,3626
54,OG-000979,FD-007,2024-10-24 22:45:00,24/10/2024 23:22,37,lightning strike,CR-09,1573
55,OG-001678,FD-009,2025-08-15 00:00:00,2025-08-15 00:08:00,8,lightning strike,CR-11,1338
56,OG-001912,FD-012,05/10/2025 11:15,2025-10-05 13:32:00,137,lightning strike,CR-05,179
57,OG-000523,FD-029,2024-07-17 19:00:00,2024-07-17 21:28:00,148,transformer fault,CR-12,2454
58,OG-002504,FD-035,2026-06-20 13:00:00,2026-06-20 16:09:00,189,vegetation contact,CR-03,823
59,OG-000580,FD-036,2024-07-30 04:15:00,2024-07-30 06:19:00,124 min,equipment failure,CR-03,2002

In [29]:
outages.isna().sum()

outage_id               0
feeder_id               0
start_ts                0
end_ts                  0
duration_min            0
cause                   0
crew_id               149
customers_affected      0
dtype: int64

In [30]:
outages.columns.tolist()

['outage_id',
 'feeder_id',
 'start_ts',
 'end_ts',
 'duration_min',
 'cause',
 'crew_id',
 'customers_affected']

In [31]:
def clean_timestamp(value):
    if pd.isna(value):
        return pd.NaT

    value = str(value).strip()

    # Unix timestamp
    if value.isdigit():
        return pd.to_datetime(int(value), unit="s")

    # Normal datetime / DD/MM/YYYY datetime
    return pd.to_datetime(value, dayfirst=True, errors="coerce")

In [32]:
outages["start_ts"] = outages["start_ts"].apply(clean_timestamp)
outages["end_ts"] = outages["end_ts"].apply(clean_timestamp)

C:\Users\Aliehme\AppData\Local\Temp\ipykernel_34636\1002482146.py:12: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  return pd.to_datetime(value, dayfirst=True, errors="coerce")

C:\Users\Aliehme\AppData\Local\Temp\ipykernel_34636\1002482146.py:12: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  return pd.to_datetime(value, dayfirst=True, errors="coerce")

In [33]:
print("Invalid start timestamps:",
      outages["start_ts"].isna().sum())

print("Invalid end timestamps:",
      outages["end_ts"].isna().sum())

Invalid start timestamps: 0
Invalid end timestamps: 0

In [34]:
outages[["start_ts", "end_ts"]].head(20)

              start_ts              end_ts
0  2025-10-08 19:15:00 2025-10-08 20:59:00
1  2024-05-06 19:45:00 2024-05-06 21:48:00
2  2026-03-31 05:30:00 2026-03-31 07:49:00
3  2025-04-08 17:30:00 2025-08-04 20:19:00
4  2024-01-08 15:15:00 2024-01-08 16:51:00
5  2025-10-07 14:15:00 2025-10-07 16:45:00
6  2025-04-14 12:15:00 2025-04-14 16:09:00
7  2025-11-25 12:15:00 2025-11-25 16:33:00
8  2025-12-04 23:15:00 2025-05-12 01:41:00
9  2024-03-22 20:30:00 2024-03-22 22:21:00
10 2024-04-12 10:00:00 2025-03-20 13:00:00
11 2025-06-21 11:15:00 2025-06-21 13:00:00
12 2024-01-03 00:45:00 2024-01-03 07:28:00
13 2024-03-10 13:45:00 2024-03-10 15:30:00
14 2024-04-26 15:30:00 2024-04-26 18:29:00
15 2025-08-24 02:30:00 2025-08-24 02:38:00
16 2025-12-19 06:30:00 2025-12-19 08:35:00
17 2026-05-18 17:30:00 2026-05-18 19:50:00
18 2025-03-06 20:30:00 2025-07-03 00:29:00
19 2026-04-09 10:00:00 2026-09-04 12:10:00

In [35]:
def clean_duration(value):
  if pd.isna(value):
    return pd.NA
  value = str(value).strip().lower()
  value = value.replace("min","").strip()

  return pd.to_numeric(value, errors="coerce")

In [36]:
outages["duration_min"] = outages["duration_min"].apply(clean_duration)

In [37]:
outages["duration_min"].dtype

dtype('int64')

In [38]:
outages[outages["duration_min"].isna()][
    ["outage_id", "duration_min"]
]

Empty DataFrame
Columns: [outage_id, duration_min]
Index: []

In [39]:
calculated_duration = (
    outages["end_ts"] - outages["start_ts"]
).dt.total_seconds() / 60

outages["calculated_duration_min"] = calculated_duration

In [40]:
outages["duration_difference"] = (
    outages["duration_min"] - outages["calculated_duration_min"]
)

outages[
    outages["duration_difference"].abs() > 1
][
    [
        "outage_id",
        "start_ts",
        "end_ts",
        "duration_min",
        "calculated_duration_min",
        "duration_difference"
    ]
].head(20)

,outage_id,start_ts,end_ts,duration_min,calculated_duration_min,duration_difference
3,OG-001615,2025-04-08 17:30:00,2025-08-04 20:19:00,169,170089.0,-169920.0
8,OG-002054,2025-12-04 23:15:00,2025-05-12 01:41:00,146,-297934.0,298080.0
10,OG-900288,2024-04-12 10:00:00,2025-03-20 13:00:00,180,492660.0,-492480.0
18,OG-001129,2025-03-06 20:30:00,2025-07-03 00:29:00,239,170159.0,-169920.0
19,OG-002256,2026-04-09 10:00:00,2026-09-04 12:10:00,130,213250.0,-213120.0
20,OG-001899,2025-01-10 09:15:00,2025-10-01 10:00:00,45,380205.0,-380160.0
24,OG-900333,2025-03-04 10:00:00,2025-04-15 13:00:00,180,60660.0,-60480.0
33,OG-001477,2025-07-02 02:00:00,2025-02-07 03:33:00,93,-208707.0,208800.0
47,OG-000605,2024-05-08 23:00:00,2024-06-08 02:13:00,193,43393.0,-43200.0
49,OG-900313,2025-03-03 10:00:00,2025-01-28 13:00:00,180,-48780.0,48960.0
50,OG-000480,2024-06-07 21:45:00,2024-07-06 23:20:00,95,41855.0,-41760.0
56,OG-001912,2025-10-05 11:15:00,2025-05-10 13:32:00,137,-212983.0,213120.0
63,OG-001007,2024-10-11 13:15:00,2024-11-10 14:29:00,74,43274.0,-43200.0
64,OG-001602,2025-08-01 13:30:00,2025-01-08 17:57:00,267,-294933.0,295200.0
65,OG-000943,2024-12-10 20:15:00,2024-10-13 00:01:00,226,-84734.0,84960.0
69,OG-000250,2024-06-05 23:00:00,2024-07-05 02:30:00,210,41970.0,-41760.0
75,OG-900334,2024-08-13 10:00:00,2025-10-05 13:00:00,180,602100.0,-601920.0
76,OG-002091,2026-03-01 14:30:00,2026-01-03 14:38:00,8,-82072.0,82080.0
77,OG-000242,2024-04-05 23:30:00,2024-05-05 01:57:00,147,41907.0,-41760.0
81,OG-000609,2024-05-08 08:15:00,2024-08-05 11:09:00,174,128334.0,-128160.0

In [41]:
outages["cause"].value_counts(dropna=False)

cause
unknown                507
lightning strike       444
storm damage           437
vegetation contact     433
pole collapse          400
planned maintenance    154
overload               147
transformer fault      142
equipment failure      141
cable theft            127
POLE COLLAPSE           21
LIGHTNING STRIKE        16
STORM DAMAGE            15
VEGETATION CONTACT      13
TRANSFORMER FAULT        6
OVERLOAD                 6
EQUIPMENT FAILURE        4
CABLE THEFT              3
UNKNOWN                  3
PLANNED MAINTENANCE      2
Name: count, dtype: int64

In [42]:
outages["cause"] = (
    outages["cause"]
    .str.strip()
    .str.lower()
)

In [43]:
outages["cause"].value_counts(dropna=False)

cause
unknown                510
lightning strike       460
storm damage           452
vegetation contact     446
pole collapse          421
planned maintenance    156
overload               153
transformer fault      148
equipment failure      145
cable theft            130
Name: count, dtype: int64

In [44]:
outages.isna().sum()

outage_id                    0
feeder_id                    0
start_ts                     0
end_ts                       0
duration_min                 0
cause                        0
crew_id                    149
customers_affected           0
calculated_duration_min      0
duration_difference          0
dtype: int64

In [45]:
outages[outages.isna().any(axis=1)].head(20)

,outage_id,feeder_id,start_ts,end_ts,duration_min,cause,crew_id,customers_affected,calculated_duration_min,duration_difference
6,OG-001222,FD-014,2025-04-14 12:15:00,2025-04-14 16:09:00,234,vegetation contact,NaN,5116,234.0,0.0
47,OG-000605,FD-036,2024-05-08 23:00:00,2024-06-08 02:13:00,193,unknown,NaN,3524,43393.0,-43200.0
61,OG-001895,FD-029,2025-09-30 05:30:00,2025-09-30 08:59:00,209,pole collapse,NaN,155,209.0,0.0
92,OG-002135,FD-005,2026-02-19 03:00:00,2026-02-19 06:54:00,234,equipment failure,NaN,3231,234.0,0.0
160,OG-001775,FD-003,2025-04-09 22:45:00,2025-04-09 22:53:00,8,planned maintenance,NaN,6986,8.0,0.0
163,OG-000700,FD-031,2024-08-23 20:00:00,2024-08-23 22:25:00,145,lightning strike,NaN,297,145.0,0.0
178,OG-001407,FD-001,2025-06-10 07:15:00,2025-10-06 08:04:00,49,storm damage,NaN,7526,169969.0,-169920.0
190,OG-000089,FD-019,2024-09-03 16:30:00,2024-09-03 17:12:00,42,planned maintenance,NaN,1034,42.0,0.0
191,OG-001092,FD-015,2025-03-02 20:45:00,2025-02-04 00:01:00,196,lightning strike,NaN,568,-38684.0,38880.0
195,OG-001887,FD-026,2025-09-28 20:45:00,2025-09-29 01:15:00,270,vegetation contact,NaN,2716,270.0,0.0
211,OG-002337,FD-015,2026-05-05 20:00:00,2026-05-05 23:01:00,181,lightning strike,NaN,144,181.0,0.0
215,OG-002443,FD-008,2026-03-06 10:15:00,2026-03-06 13:37:00,202,lightning strike,NaN,4446,202.0,0.0
222,OG-001452,FD-013,2025-06-26 10:00:00,2025-06-26 13:13:00,193,vegetation contact,NaN,2560,193.0,0.0
255,OG-000912,FD-016,2024-03-10 01:30:00,2024-03-10 04:43:00,193,pole collapse,NaN,161,193.0,0.0
272,OG-001659,FD-011,2025-12-08 21:45:00,2025-12-08 23:41:00,116,overload,NaN,5115,116.0,0.0
278,OG-001583,FD-015,2025-07-26 03:00:00,2025-07-26 06:20:00,200,pole collapse,NaN,857,200.0,0.0
316,OG-000605,FD-036,2024-05-08 23:00:00,2024-06-08 02:13:00,193,unknown,NaN,3524,43393.0,-43200.0
323,OG-002053,FD-004,2025-02-12 11:00:00,2025-02-12 12:34:00,94,planned maintenance,NaN,2212,94.0,0.0
376,OG-001101,FD-032,2025-02-16 10:15:00,2025-02-16 15:40:00,325,overload,NaN,1254,325.0,0.0
392,OG-000468,FD-020,2024-04-07 22:00:00,2024-04-07 23:57:00,117,vegetation contact,NaN,2673,117.0,0.0

In [46]:
for column in outages.columns:
    print(f"\n{column}")
    print(outages[column].isna().sum())

outage_id
0

feeder_id
0

start_ts
0

end_ts
0

duration_min
0

cause
0

crew_id
149

customers_affected
0

calculated_duration_min
0

duration_difference
0

In [47]:
outages[
    outages["outage_id"].isna() |
    outages["feeder_id"].isna()
]

Empty DataFrame
Columns: [outage_id, feeder_id, start_ts, end_ts, duration_min, cause, crew_id, customers_affected, calculated_duration_min, duration_difference]
Index: []

In [48]:
duplicates = outages[outages.duplicated(keep=False)]

print("Duplicate rows:", len(duplicates))

Duplicate rows: 260

In [49]:
duplicates.sort_values("outage_id").head(30)

,outage_id,feeder_id,start_ts,end_ts,duration_min,cause,crew_id,customers_affected,calculated_duration_min,duration_difference
1364,OG-000006,FD-006,2024-08-01 02:30:00,2024-08-01 07:51:00,321,lightning strike,CR-16,3994,321.0,0.0
2276,OG-000006,FD-006,2024-08-01 02:30:00,2024-08-01 07:51:00,321,lightning strike,CR-16,3994,321.0,0.0
516,OG-000010,FD-015,2024-10-01 00:30:00,2024-10-01 00:38:00,8,overload,CR-15,217,8.0,0.0
2637,OG-000010,FD-015,2024-10-01 00:30:00,2024-10-01 00:38:00,8,overload,CR-15,217,8.0,0.0
1766,OG-000030,FD-036,2024-01-21 09:30:00,2024-01-21 12:53:00,203,unknown,CR-16,3420,203.0,0.0
1503,OG-000030,FD-036,2024-01-21 09:30:00,2024-01-21 12:53:00,203,unknown,CR-16,3420,203.0,0.0
1420,OG-000037,FD-022,2024-01-25 08:00:00,2024-01-25 14:55:00,415,lightning strike,CR-03,628,415.0,0.0
2574,OG-000037,FD-022,2024-01-25 08:00:00,2024-01-25 14:55:00,415,lightning strike,CR-03,628,415.0,0.0
406,OG-000052,FD-031,2024-11-02 20:30:00,2024-11-02 22:28:00,118,equipment failure,CR-09,1270,118.0,0.0
2153,OG-000052,FD-031,2024-11-02 20:30:00,2024-11-02 22:28:00,118,equipment failure,CR-09,1270,118.0,0.0
2809,OG-000059,FD-022,2024-02-19 07:30:00,2024-02-19 09:18:00,108,lightning strike,CR-01,415,108.0,0.0
1421,OG-000059,FD-022,2024-02-19 07:30:00,2024-02-19 09:18:00,108,lightning strike,CR-01,415,108.0,0.0
410,OG-000135,FD-002,2024-03-27 13:00:00,2024-03-27 14:20:00,80,cable theft,CR-14,5097,80.0,0.0
2946,OG-000135,FD-002,2024-03-27 13:00:00,2024-03-27 14:20:00,80,cable theft,CR-14,5097,80.0,0.0
2187,OG-000179,FD-036,2024-04-12 05:00:00,2024-12-04 05:08:00,8,equipment failure,CR-12,1798,339848.0,-339840.0
2855,OG-000179,FD-036,2024-04-12 05:00:00,2024-12-04 05:08:00,8,equipment failure,CR-12,1798,339848.0,-339840.0
2083,OG-000183,FD-030,2024-04-13 12:30:00,2024-04-13 14:02:00,92,vegetation contact,CR-04,5423,92.0,0.0
2698,OG-000183,FD-030,2024-04-13 12:30:00,2024-04-13 14:02:00,92,vegetation contact,CR-04,5423,92.0,0.0
582,OG-000185,FD-028,2024-04-15 10:15:00,2024-04-15 12:56:00,161,vegetation contact,CR-04,3239,161.0,0.0
1999,OG-000185,FD-028,2024-04-15 10:15:00,2024-04-15 12:56:00,161,vegetation contact,CR-04,3239,161.0,0.0
1892,OG-000200,FD-023,2024-04-20 01:15:00,2024-04-20 04:57:00,222,storm damage,CR-12,72,222.0,0.0
2439,OG-000200,FD-023,2024-04-20 01:15:00,2024-04-20 04:57:00,222,storm damage,CR-12,72,222.0,0.0
113,OG-000225,FD-026,2024-04-29 01:30:00,2024-04-29 05:48:00,258,lightning strike,CR-10,657,258.0,0.0
478,OG-000225,FD-026,2024-04-29 01:30:00,2024-04-29 05:48:00,258,lightning strike,CR-10,657,258.0,0.0
1832,OG-000242,FD-008,2024-04-05 23:30:00,2024-05-05 01:57:00,147,lightning strike,CR-09,3800,41907.0,-41760.0
77,OG-000242,FD-008,2024-04-05 23:30:00,2024-05-05 01:57:00,147,lightning strike,CR-09,3800,41907.0,-41760.0
2035,OG-000260,FD-036,2024-05-09 15:30:00,2024-09-05 19:15:00,225,storm damage,NaN,3949,171585.0,-171360.0
2937,OG-000260,FD-036,2024-05-09 15:30:00,2024-09-05 19:15:00,225,storm damage,NaN,3949,171585.0,-171360.0
2913,OG-000262,FD-020,2024-09-05 03:15:00,2024-09-05 05:15:00,120,lightning strike,CR-04,2903,120.0,0.0
1641,OG-000262,FD-020,2024-09-05 03:15:00,2024-09-05 05:15:00,120,lightning strike,CR-04,2903,120.0,0.0

In [50]:
duplicate_ids = outages[
    outages["outage_id"].duplicated(keep=False)
]

print("Rows with duplicated outage IDs:", len(duplicate_ids))

Rows with duplicated outage IDs: 260

In [51]:
duplicate_ids.sort_values("outage_id").head(30)

,outage_id,feeder_id,start_ts,end_ts,duration_min,cause,crew_id,customers_affected,calculated_duration_min,duration_difference
1364,OG-000006,FD-006,2024-08-01 02:30:00,2024-08-01 07:51:00,321,lightning strike,CR-16,3994,321.0,0.0
2276,OG-000006,FD-006,2024-08-01 02:30:00,2024-08-01 07:51:00,321,lightning strike,CR-16,3994,321.0,0.0
516,OG-000010,FD-015,2024-10-01 00:30:00,2024-10-01 00:38:00,8,overload,CR-15,217,8.0,0.0
2637,OG-000010,FD-015,2024-10-01 00:30:00,2024-10-01 00:38:00,8,overload,CR-15,217,8.0,0.0
1766,OG-000030,FD-036,2024-01-21 09:30:00,2024-01-21 12:53:00,203,unknown,CR-16,3420,203.0,0.0
1503,OG-000030,FD-036,2024-01-21 09:30:00,2024-01-21 12:53:00,203,unknown,CR-16,3420,203.0,0.0
1420,OG-000037,FD-022,2024-01-25 08:00:00,2024-01-25 14:55:00,415,lightning strike,CR-03,628,415.0,0.0
2574,OG-000037,FD-022,2024-01-25 08:00:00,2024-01-25 14:55:00,415,lightning strike,CR-03,628,415.0,0.0
406,OG-000052,FD-031,2024-11-02 20:30:00,2024-11-02 22:28:00,118,equipment failure,CR-09,1270,118.0,0.0
2153,OG-000052,FD-031,2024-11-02 20:30:00,2024-11-02 22:28:00,118,equipment failure,CR-09,1270,118.0,0.0
2809,OG-000059,FD-022,2024-02-19 07:30:00,2024-02-19 09:18:00,108,lightning strike,CR-01,415,108.0,0.0
1421,OG-000059,FD-022,2024-02-19 07:30:00,2024-02-19 09:18:00,108,lightning strike,CR-01,415,108.0,0.0
410,OG-000135,FD-002,2024-03-27 13:00:00,2024-03-27 14:20:00,80,cable theft,CR-14,5097,80.0,0.0
2946,OG-000135,FD-002,2024-03-27 13:00:00,2024-03-27 14:20:00,80,cable theft,CR-14,5097,80.0,0.0
2187,OG-000179,FD-036,2024-04-12 05:00:00,2024-12-04 05:08:00,8,equipment failure,CR-12,1798,339848.0,-339840.0
2855,OG-000179,FD-036,2024-04-12 05:00:00,2024-12-04 05:08:00,8,equipment failure,CR-12,1798,339848.0,-339840.0
2083,OG-000183,FD-030,2024-04-13 12:30:00,2024-04-13 14:02:00,92,vegetation contact,CR-04,5423,92.0,0.0
2698,OG-000183,FD-030,2024-04-13 12:30:00,2024-04-13 14:02:00,92,vegetation contact,CR-04,5423,92.0,0.0
582,OG-000185,FD-028,2024-04-15 10:15:00,2024-04-15 12:56:00,161,vegetation contact,CR-04,3239,161.0,0.0
1999,OG-000185,FD-028,2024-04-15 10:15:00,2024-04-15 12:56:00,161,vegetation contact,CR-04,3239,161.0,0.0
1892,OG-000200,FD-023,2024-04-20 01:15:00,2024-04-20 04:57:00,222,storm damage,CR-12,72,222.0,0.0
2439,OG-000200,FD-023,2024-04-20 01:15:00,2024-04-20 04:57:00,222,storm damage,CR-12,72,222.0,0.0
113,OG-000225,FD-026,2024-04-29 01:30:00,2024-04-29 05:48:00,258,lightning strike,CR-10,657,258.0,0.0
478,OG-000225,FD-026,2024-04-29 01:30:00,2024-04-29 05:48:00,258,lightning strike,CR-10,657,258.0,0.0
1832,OG-000242,FD-008,2024-04-05 23:30:00,2024-05-05 01:57:00,147,lightning strike,CR-09,3800,41907.0,-41760.0
77,OG-000242,FD-008,2024-04-05 23:30:00,2024-05-05 01:57:00,147,lightning strike,CR-09,3800,41907.0,-41760.0
2035,OG-000260,FD-036,2024-05-09 15:30:00,2024-09-05 19:15:00,225,storm damage,NaN,3949,171585.0,-171360.0
2937,OG-000260,FD-036,2024-05-09 15:30:00,2024-09-05 19:15:00,225,storm damage,NaN,3949,171585.0,-171360.0
2913,OG-000262,FD-020,2024-09-05 03:15:00,2024-09-05 05:15:00,120,lightning strike,CR-04,2903,120.0,0.0
1641,OG-000262,FD-020,2024-09-05 03:15:00,2024-09-05 05:15:00,120,lightning strike,CR-04,2903,120.0,0.0

In [52]:
outages_clean = outages.drop_duplicates().copy()

In [53]:
print("Before:", len(outages))
print("After:", len(outages_clean))

Before: 3021
After: 2891

In [54]:
valid_feeders = set(feeders["feeder_id"].dropna())

In [55]:
invalid_feeders = outages_clean[
    ~outages_clean["feeder_id"].isin(valid_feeders)
]

print("Invalid feeder rows:", len(invalid_feeders))

Invalid feeder rows: 350

In [56]:
invalid_feeders[
    ["outage_id", "feeder_id", "start_ts", "end_ts", "cause"]
].head(30)

     outage_id feeder_id            start_ts              end_ts    cause
10   OG-900288   FD-9288 2024-04-12 10:00:00 2025-03-20 13:00:00  unknown
24   OG-900333   FD-9333 2025-03-04 10:00:00 2025-04-15 13:00:00  unknown
49   OG-900313   FD-9313 2025-03-03 10:00:00 2025-01-28 13:00:00  unknown
75   OG-900334   FD-9334 2024-08-13 10:00:00 2025-10-05 13:00:00  unknown
84   OG-900030    FD-930 2024-07-25 10:00:00 2025-06-11 13:00:00  unknown
86   OG-900211   FD-9211 2025-02-12 10:00:00 2025-07-26 13:00:00  unknown
94   OG-900312   FD-9312 2025-06-03 10:00:00 2025-04-07 13:00:00  unknown
101  OG-900253   FD-9253 2025-06-12 10:00:00 2025-06-21 13:00:00  unknown
105  OG-900297   FD-9297 2025-11-01 10:00:00 2025-11-05 13:00:00  unknown
110  OG-900162   FD-9162 2024-10-16 10:00:00 2025-09-18 13:00:00  unknown
111  OG-900160   FD-9160 2025-12-03 10:00:00 2025-12-11 13:00:00  unknown
140  OG-900061    FD-961 2025-03-07 10:00:00 2025-05-10 13:00:00  unknown
146  OG-900347   FD-9347 2024-07-09 10:00:00 2025-07-17 13:00:00  unknown
152  OG-900157   FD-9157 2024-12-11 10:00:00 2025-03-04 13:00:00  unknown
154  OG-900062    FD-962 2024-11-19 10:00:00 2025-02-18 13:00:00  unknown
159  OG-900138   FD-9138 2024-09-12 10:00:00 2025-05-21 13:00:00  unknown
166  OG-900142   FD-9142 2025-05-07 10:00:00 2025-04-10 13:00:00  unknown
202  OG-900057    FD-957 2024-04-06 10:00:00 2025-08-17 13:00:00  unknown
208  OG-900278   FD-9278 2025-09-22 10:00:00 2025-10-07 13:00:00  unknown
210  OG-900044    FD-944 2025-04-14 10:00:00 2025-04-13 13:00:00  unknown
224  OG-900234   FD-9234 2024-03-11 10:00:00 2025-07-27 13:00:00  unknown
244  OG-900336   FD-9336 2025-02-11 10:00:00 2025-12-07 13:00:00  unknown
247  OG-900054    FD-954 2025-05-11 10:00:00 2025-08-24 13:00:00  unknown
257  OG-900104   FD-9104 2024-09-06 10:00:00 2025-01-25 13:00:00  unknown
266  OG-900265   FD-9265 2024-02-17 10:00:00 2025-08-06 13:00:00  unknown
268  OG-900123   FD-9123 2024-10-03 10:00:00 2025-02-08 13:00:00  unknown
271  OG-900261   FD-9261 2024-08-18 10:00:00 2025-06-09 13:00:00  unknown
281  OG-900309   FD-9309 2025-12-24 10:00:00 2025-10-08 13:00:00  unknown
282  OG-900286   FD-9286 2024-07-23 10:00:00 2025-09-06 13:00:00  unknown
284  OG-900338   FD-9338 2025-03-05 10:00:00 2025-11-09 13:00:00  unknown

In [57]:
outages_clean["start_ts"] = pd.to_datetime(
    outages_clean["start_ts"],
    errors="coerce"
)

outages_clean["end_ts"] = pd.to_datetime(
    outages_clean["end_ts"],
    errors="coerce"
)

In [58]:
bad_timestamps = outages_clean[
    outages_clean["start_ts"].isna() |
    outages_clean["end_ts"].isna()
]

print("Bad timestamps:", len(bad_timestamps))

Bad timestamps: 0

In [59]:
bad_order = outages_clean[
    outages_clean["end_ts"] < outages_clean["start_ts"]
]

print("End before start:", len(bad_order))

End before start: 282

In [60]:
bad_order[
    ["outage_id", "start_ts", "end_ts", "duration_min"]
].head(20)

     outage_id            start_ts              end_ts  duration_min
8    OG-002054 2025-12-04 23:15:00 2025-05-12 01:41:00           146
33   OG-001477 2025-07-02 02:00:00 2025-02-07 03:33:00            93
49   OG-900313 2025-03-03 10:00:00 2025-01-28 13:00:00           180
56   OG-001912 2025-10-05 11:15:00 2025-05-10 13:32:00           137
64   OG-001602 2025-08-01 13:30:00 2025-01-08 17:57:00           267
65   OG-000943 2024-12-10 20:15:00 2024-10-13 00:01:00           226
76   OG-002091 2026-03-01 14:30:00 2026-01-03 14:38:00             8
83   OG-000150 2024-04-02 05:00:00 2024-02-04 09:50:00           290
94   OG-900312 2025-06-03 10:00:00 2025-04-07 13:00:00           180
137  OG-000378 2024-11-06 15:00:00 2024-06-11 18:11:00           191
142  OG-000487 2024-08-07 09:30:00 2024-07-08 12:19:00           169
158  OG-001293 2025-08-05 01:00:00 2025-05-08 04:46:00           226
166  OG-900142 2025-05-07 10:00:00 2025-04-10 13:00:00           180
177  OG-000999 2024-11-02 16:45:00 2024-02-11 18:59:00           134
191  OG-001092 2025-03-02 20:45:00 2025-02-04 00:01:00           196
197  OG-000594 2024-08-03 16:15:00 2024-03-08 18:03:00           108
207  OG-001653 2025-11-08 22:30:00 2025-08-12 02:03:00           213
210  OG-900044 2025-04-14 10:00:00 2025-04-13 13:00:00           180
236  OG-000094 2024-11-03 00:45:00 2024-03-11 05:13:00           268
237  OG-002119 2026-10-02 16:45:00 2026-02-10 17:59:00            74

In [61]:
outages_clean["duration_min"] = pd.to_numeric(
    outages_clean["duration_min"],
    errors="coerce"
)

In [62]:
bad_duration = outages_clean[
    outages_clean["duration_min"].isna()
]

print("Invalid duration rows:", len(bad_duration))

Invalid duration rows: 0

In [63]:
outages_clean["calculated_duration_min"] = (
    outages_clean["end_ts"] - outages_clean["start_ts"]
).dt.total_seconds() / 60

In [64]:
duration_mismatch = outages_clean[
    (outages_clean["duration_min"] - outages_clean["calculated_duration_min"]).abs() > 1
]

print("Duration mismatches:", len(duration_mismatch))

Duration mismatches: 786

In [65]:
duration_mismatch[
    [
        "outage_id",
        "start_ts",
        "end_ts",
        "duration_min",
        "calculated_duration_min"
    ]
].head(20)

,outage_id,start_ts,end_ts,duration_min,calculated_duration_min
3,OG-001615,2025-04-08 17:30:00,2025-08-04 20:19:00,169,170089.0
8,OG-002054,2025-12-04 23:15:00,2025-05-12 01:41:00,146,-297934.0
10,OG-900288,2024-04-12 10:00:00,2025-03-20 13:00:00,180,492660.0
18,OG-001129,2025-03-06 20:30:00,2025-07-03 00:29:00,239,170159.0
19,OG-002256,2026-04-09 10:00:00,2026-09-04 12:10:00,130,213250.0
20,OG-001899,2025-01-10 09:15:00,2025-10-01 10:00:00,45,380205.0
24,OG-900333,2025-03-04 10:00:00,2025-04-15 13:00:00,180,60660.0
33,OG-001477,2025-07-02 02:00:00,2025-02-07 03:33:00,93,-208707.0
47,OG-000605,2024-05-08 23:00:00,2024-06-08 02:13:00,193,43393.0
49,OG-900313,2025-03-03 10:00:00,2025-01-28 13:00:00,180,-48780.0
50,OG-000480,2024-06-07 21:45:00,2024-07-06 23:20:00,95,41855.0
56,OG-001912,2025-10-05 11:15:00,2025-05-10 13:32:00,137,-212983.0
63,OG-001007,2024-10-11 13:15:00,2024-11-10 14:29:00,74,43274.0
64,OG-001602,2025-08-01 13:30:00,2025-01-08 17:57:00,267,-294933.0
65,OG-000943,2024-12-10 20:15:00,2024-10-13 00:01:00,226,-84734.0
69,OG-000250,2024-06-05 23:00:00,2024-07-05 02:30:00,210,41970.0
75,OG-900334,2024-08-13 10:00:00,2025-10-05 13:00:00,180,602100.0
76,OG-002091,2026-03-01 14:30:00,2026-01-03 14:38:00,8,-82072.0
77,OG-000242,2024-04-05 23:30:00,2024-05-05 01:57:00,147,41907.0
81,OG-000609,2024-05-08 08:15:00,2024-08-05 11:09:00,174,128334.0

In [66]:
outages_clean["customers_affected"] = pd.to_numeric(
    outages_clean["customers_affected"],
    errors="coerce"
)

In [67]:
bad_customers = outages_clean[
    outages_clean["customers_affected"].isna()
]

print("Invalid customer values:", len(bad_customers))

Invalid customer values: 0

In [68]:
negative_customers = outages_clean[
    outages_clean["customers_affected"] < 0
]

print("Negative customer values:", len(negative_customers))

Negative customer values: 0

In [69]:
negative_customers[
    ["outage_id", "customers_affected"]
].head(20)

Empty DataFrame
Columns: [outage_id, customers_affected]
Index: []

In [70]:
outages_clean["cause"] = outages_clean["cause"].str.strip().str.lower()

In [71]:
outages_clean["cause"].unique()

<StringArray>
[   'lightning strike',        'storm damage',  'vegetation contact',
       'pole collapse',             'unknown',            'overload',
   'transformer fault', 'planned maintenance',   'equipment failure',
         'cable theft']
Length: 10, dtype: str

In [72]:
outages_clean["cause"].value_counts(dropna=False)

cause
unknown                489
lightning strike       438
storm damage           434
vegetation contact     426
pole collapse          410
overload               146
planned maintenance    146
transformer fault      140
equipment failure      139
cable theft            123
Name: count, dtype: int64

In [73]:
duplicate_outage_ids = outages_clean[
    outages_clean["outage_id"].duplicated(keep=False)
]

print("Duplicated outage IDs:", len(duplicate_outage_ids))

Duplicated outage IDs: 0

In [74]:
duplicate_outage_ids.sort_values("outage_id").head(30)

Empty DataFrame
Columns: [outage_id, feeder_id, start_ts, end_ts, duration_min, cause, crew_id, customers_affected, calculated_duration_min, duration_difference]
Index: []

In [75]:
invalid_outage_ids = outages_clean[
    ~outages_clean["outage_id"].str.match(
        r"^OG-\d{6}$",
        na=False
    )
]

print("Invalid outage IDs:", len(invalid_outage_ids))

Invalid outage IDs: 0

In [76]:
invalid_outage_ids[
    ["outage_id", "feeder_id"]
].head(30)

Empty DataFrame
Columns: [outage_id, feeder_id]
Index: []

In [77]:
valid_feeder_ids = set(feeders["feeder_id"].dropna())

invalid_feeder_rows = outages_clean[
    ~outages_clean["feeder_id"].isin(valid_feeder_ids)
]

print("Invalid feeder rows:", len(invalid_feeder_rows))

Invalid feeder rows: 350

In [78]:
invalid_feeder_rows[
    ["outage_id", "feeder_id", "start_ts", "end_ts", "duration_min"]
].head(30)

     outage_id feeder_id            start_ts              end_ts  duration_min
10   OG-900288   FD-9288 2024-04-12 10:00:00 2025-03-20 13:00:00           180
24   OG-900333   FD-9333 2025-03-04 10:00:00 2025-04-15 13:00:00           180
49   OG-900313   FD-9313 2025-03-03 10:00:00 2025-01-28 13:00:00           180
75   OG-900334   FD-9334 2024-08-13 10:00:00 2025-10-05 13:00:00           180
84   OG-900030    FD-930 2024-07-25 10:00:00 2025-06-11 13:00:00           180
86   OG-900211   FD-9211 2025-02-12 10:00:00 2025-07-26 13:00:00           180
94   OG-900312   FD-9312 2025-06-03 10:00:00 2025-04-07 13:00:00           180
101  OG-900253   FD-9253 2025-06-12 10:00:00 2025-06-21 13:00:00           180
105  OG-900297   FD-9297 2025-11-01 10:00:00 2025-11-05 13:00:00           180
110  OG-900162   FD-9162 2024-10-16 10:00:00 2025-09-18 13:00:00           180
111  OG-900160   FD-9160 2025-12-03 10:00:00 2025-12-11 13:00:00           180
140  OG-900061    FD-961 2025-03-07 10:00:00 2025-05-10 13:00:00           180
146  OG-900347   FD-9347 2024-07-09 10:00:00 2025-07-17 13:00:00           180
152  OG-900157   FD-9157 2024-12-11 10:00:00 2025-03-04 13:00:00           180
154  OG-900062    FD-962 2024-11-19 10:00:00 2025-02-18 13:00:00           180
159  OG-900138   FD-9138 2024-09-12 10:00:00 2025-05-21 13:00:00           180
166  OG-900142   FD-9142 2025-05-07 10:00:00 2025-04-10 13:00:00           180
202  OG-900057    FD-957 2024-04-06 10:00:00 2025-08-17 13:00:00           180
208  OG-900278   FD-9278 2025-09-22 10:00:00 2025-10-07 13:00:00           180
210  OG-900044    FD-944 2025-04-14 10:00:00 2025-04-13 13:00:00           180
224  OG-900234   FD-9234 2024-03-11 10:00:00 2025-07-27 13:00:00           180
244  OG-900336   FD-9336 2025-02-11 10:00:00 2025-12-07 13:00:00           180
247  OG-900054    FD-954 2025-05-11 10:00:00 2025-08-24 13:00:00           180
257  OG-900104   FD-9104 2024-09-06 10:00:00 2025-01-25 13:00:00           180
266  OG-900265   FD-9265 2024-02-17 10:00:00 2025-08-06 13:00:00           180
268  OG-900123   FD-9123 2024-10-03 10:00:00 2025-02-08 13:00:00           180
271  OG-900261   FD-9261 2024-08-18 10:00:00 2025-06-09 13:00:00           180
281  OG-900309   FD-9309 2025-12-24 10:00:00 2025-10-08 13:00:00           180
282  OG-900286   FD-9286 2024-07-23 10:00:00 2025-09-06 13:00:00           180
284  OG-900338   FD-9338 2025-03-05 10:00:00 2025-11-09 13:00:00           180

In [79]:
outages_clean["crew_id"].isna().sum()

np.int64(138)

In [80]:
outages_clean["crew_id"].value_counts(dropna=False).head(30)

crew_id
CR-01    474
CR-10    153
CR-04    148
CR-07    145
CR-06    145
CR-13    140
NaN      138
CR-15    138
CR-02    135
CR-08    135
CR-11    132
CR-09    131
CR-16    131
CR-05    129
CR-12    129
CR-03    127
CR-14    126
CR-18    118
CR-17    117
Name: count, dtype: int64

In [81]:
invalid_crew_ids = outages_clean[
    ~outages_clean["crew_id"].str.match(
        r"^CR-\d{2}$",
        na=False
    )
]

print("Invalid crew IDs:", len(invalid_crew_ids))

Invalid crew IDs: 138

In [82]:
outages_clean["crew_id"] = (
    outages_clean["crew_id"]
    .str.strip()
)

In [83]:
bad_records = outages_clean[
    (
        outages_clean["end_ts"] < outages_clean["start_ts"]
    )
    |
    (
        outages_clean["duration_difference"].abs() > 1
    )
]

print("Problematic outage records:", len(bad_records))

bad_records[
    [
        "outage_id",
        "feeder_id",
        "start_ts",
        "end_ts",
        "duration_min",
        "calculated_duration_min",
        "cause"
    ]
].head(50)

Problematic outage records: 786

,outage_id,feeder_id,start_ts,end_ts,duration_min,calculated_duration_min,cause
3,OG-001615,FD-036,2025-04-08 17:30:00,2025-08-04 20:19:00,169,170089.0,storm damage
8,OG-002054,FD-033,2025-12-04 23:15:00,2025-05-12 01:41:00,146,-297934.0,pole collapse
10,OG-900288,FD-9288,2024-04-12 10:00:00,2025-03-20 13:00:00,180,492660.0,unknown
18,OG-001129,FD-036,2025-03-06 20:30:00,2025-07-03 00:29:00,239,170159.0,vegetation contact
19,OG-002256,FD-033,2026-04-09 10:00:00,2026-09-04 12:10:00,130,213250.0,transformer fault
20,OG-001899,FD-001,2025-01-10 09:15:00,2025-10-01 10:00:00,45,380205.0,storm damage
24,OG-900333,FD-9333,2025-03-04 10:00:00,2025-04-15 13:00:00,180,60660.0,unknown
33,OG-001477,FD-012,2025-07-02 02:00:00,2025-02-07 03:33:00,93,-208707.0,equipment failure
47,OG-000605,FD-036,2024-05-08 23:00:00,2024-06-08 02:13:00,193,43393.0,unknown
49,OG-900313,FD-9313,2025-03-03 10:00:00,2025-01-28 13:00:00,180,-48780.0,unknown
50,OG-000480,FD-004,2024-06-07 21:45:00,2024-07-06 23:20:00,95,41855.0,planned maintenance
56,OG-001912,FD-012,2025-10-05 11:15:00,2025-05-10 13:32:00,137,-212983.0,lightning strike
63,OG-001007,FD-021,2024-10-11 13:15:00,2024-11-10 14:29:00,74,43274.0,overload
64,OG-001602,FD-023,2025-08-01 13:30:00,2025-01-08 17:57:00,267,-294933.0,lightning strike
65,OG-000943,FD-035,2024-12-10 20:15:00,2024-10-13 00:01:00,226,-84734.0,storm damage
69,OG-000250,FD-031,2024-06-05 23:00:00,2024-07-05 02:30:00,210,41970.0,pole collapse
75,OG-900334,FD-9334,2024-08-13 10:00:00,2025-10-05 13:00:00,180,602100.0,unknown
76,OG-002091,FD-030,2026-03-01 14:30:00,2026-01-03 14:38:00,8,-82072.0,unknown
77,OG-000242,FD-008,2024-04-05 23:30:00,2024-05-05 01:57:00,147,41907.0,lightning strike
81,OG-000609,FD-019,2024-05-08 08:15:00,2024-08-05 11:09:00,174,128334.0,vegetation contact
83,OG-000150,FD-011,2024-04-02 05:00:00,2024-02-04 09:50:00,290,-83230.0,lightning strike
84,OG-900030,FD-930,2024-07-25 10:00:00,2025-06-11 13:00:00,180,462420.0,unknown
86,OG-900211,FD-9211,2025-02-12 10:00:00,2025-07-26 13:00:00,180,236340.0,unknown
93,OG-001046,FD-014,2024-07-12 23:45:00,2024-12-07 23:53:00,8,213128.0,unknown
94,OG-900312,FD-9312,2025-06-03 10:00:00,2025-04-07 13:00:00,180,-81900.0,unknown
95,OG-001390,FD-005,2025-05-06 06:15:00,2025-06-05 11:08:00,293,43493.0,pole collapse
96,OG-000789,FD-015,2024-08-09 21:15:00,2024-09-09 03:15:00,360,43560.0,pole collapse
100,OG-000470,FD-022,2024-04-07 16:00:00,2024-07-04 17:37:00,97,126817.0,vegetation contact
101,OG-900253,FD-9253,2025-06-12 10:00:00,2025-06-21 13:00:00,180,13140.0,unknown
105,OG-900297,FD-9297,2025-11-01 10:00:00,2025-11-05 13:00:00,180,5940.0,unknown
106,OG-000921,FD-029,2024-05-10 21:15:00,2024-06-10 00:56:00,221,43421.0,pole collapse
110,OG-900162,FD-9162,2024-10-16 10:00:00,2025-09-18 13:00:00,180,485460.0,unknown
111,OG-900160,FD-9160,2025-12-03 10:00:00,2025-12-11 13:00:00,180,11700.0,unknown
115,OG-002175,FD-033,2026-03-07 23:00:00,2026-08-03 02:36:00,216,213336.0,cable theft
116,OG-001274,FD-025,2025-03-05 22:00:00,2025-04-05 01:21:00,201,43401.0,pole collapse
130,OG-002181,FD-024,2026-09-03 20:00:00,2026-10-03 00:54:00,294,42054.0,pole collapse
137,OG-000378,FD-027,2024-11-06 15:00:00,2024-06-11 18:11:00,191,-212929.0,vegetation contact
140,OG-900061,FD-961,2025-03-07 10:00:00,2025-05-10 13:00:00,180,92340.0,unknown
142,OG-000487,FD-029,2024-08-07 09:30:00,2024-07-08 12:19:00,169,-43031.0,pole collapse
146,OG-900347,FD-9347,2024-07-09 10:00:00,2025-07-17 13:00:00,180,537300.0,unknown
147,OG-002463,FD-008,2026-06-09 06:00:00,2026-09-06 09:31:00,211,128371.0,vegetation contact
152,OG-900157,FD-9157,2024-12-11 10:00:00,2025-03-04 13:00:00,180,119700.0,unknown
154,OG-900062,FD-962,2024-11-19 10:00:00,2025-02-18 13:00:00,180,131220.0,unknown
158,OG-001293,FD-006,2025-08-05 01:00:00,2025-05-08 04:46:00,226,-127934.0,vegetation contact
159,OG-900138,FD-9138,2024-09-12 10:00:00,2025-05-21 13:00:00,180,361620.0,unknown
166,OG-900142,FD-9142,2025-05-07 10:00:00,2025-04-10 13:00:00,180,-38700.0,unknown
168,OG-001073,FD-003,2025-01-09 08:15:00,2025-09-01 11:19:00,184,338584.0,cable theft
177,OG-000999,FD-035,2024-11-02 16:45:00,2024-02-11 18:59:00,134,-381466.0,planned maintenance
178,OG-001407,FD-001,2025-06-10 07:15:00,2025-10-06 08:04:00,49,169969.0,storm damage
191,OG-001092,FD-015,2025-03-02 20:45:00,2025-02-04 00:01:00,196,-38684.0,lightning strike

In [84]:
outages_clean["duration_mismatch"] = (
    outages_clean["duration_difference"].abs() > 1
)

In [85]:
outages_clean["invalid_time_order"] = (
    outages_clean["end_ts"] < outages_clean["start_ts"]
)

In [86]:
outages_clean["data_quality_issue"] = (
    outages_clean["duration_mismatch"]
    | outages_clean["invalid_time_order"]
)

In [87]:
print(
    outages_clean["data_quality_issue"].value_counts()
)

data_quality_issue
False    2105
True      786
Name: count, dtype: int64

In [88]:
outages_clean[
    outages_clean["data_quality_issue"]
][[
    "outage_id",
    "start_ts",
    "end_ts",
    "duration_min",
    "calculated_duration_min",
    "cause"
]].head(50)

,outage_id,start_ts,end_ts,duration_min,calculated_duration_min,cause
3,OG-001615,2025-04-08 17:30:00,2025-08-04 20:19:00,169,170089.0,storm damage
8,OG-002054,2025-12-04 23:15:00,2025-05-12 01:41:00,146,-297934.0,pole collapse
10,OG-900288,2024-04-12 10:00:00,2025-03-20 13:00:00,180,492660.0,unknown
18,OG-001129,2025-03-06 20:30:00,2025-07-03 00:29:00,239,170159.0,vegetation contact
19,OG-002256,2026-04-09 10:00:00,2026-09-04 12:10:00,130,213250.0,transformer fault
20,OG-001899,2025-01-10 09:15:00,2025-10-01 10:00:00,45,380205.0,storm damage
24,OG-900333,2025-03-04 10:00:00,2025-04-15 13:00:00,180,60660.0,unknown
33,OG-001477,2025-07-02 02:00:00,2025-02-07 03:33:00,93,-208707.0,equipment failure
47,OG-000605,2024-05-08 23:00:00,2024-06-08 02:13:00,193,43393.0,unknown
49,OG-900313,2025-03-03 10:00:00,2025-01-28 13:00:00,180,-48780.0,unknown
50,OG-000480,2024-06-07 21:45:00,2024-07-06 23:20:00,95,41855.0,planned maintenance
56,OG-001912,2025-10-05 11:15:00,2025-05-10 13:32:00,137,-212983.0,lightning strike
63,OG-001007,2024-10-11 13:15:00,2024-11-10 14:29:00,74,43274.0,overload
64,OG-001602,2025-08-01 13:30:00,2025-01-08 17:57:00,267,-294933.0,lightning strike
65,OG-000943,2024-12-10 20:15:00,2024-10-13 00:01:00,226,-84734.0,storm damage
69,OG-000250,2024-06-05 23:00:00,2024-07-05 02:30:00,210,41970.0,pole collapse
75,OG-900334,2024-08-13 10:00:00,2025-10-05 13:00:00,180,602100.0,unknown
76,OG-002091,2026-03-01 14:30:00,2026-01-03 14:38:00,8,-82072.0,unknown
77,OG-000242,2024-04-05 23:30:00,2024-05-05 01:57:00,147,41907.0,lightning strike
81,OG-000609,2024-05-08 08:15:00,2024-08-05 11:09:00,174,128334.0,vegetation contact
83,OG-000150,2024-04-02 05:00:00,2024-02-04 09:50:00,290,-83230.0,lightning strike
84,OG-900030,2024-07-25 10:00:00,2025-06-11 13:00:00,180,462420.0,unknown
86,OG-900211,2025-02-12 10:00:00,2025-07-26 13:00:00,180,236340.0,unknown
93,OG-001046,2024-07-12 23:45:00,2024-12-07 23:53:00,8,213128.0,unknown
94,OG-900312,2025-06-03 10:00:00,2025-04-07 13:00:00,180,-81900.0,unknown
95,OG-001390,2025-05-06 06:15:00,2025-06-05 11:08:00,293,43493.0,pole collapse
96,OG-000789,2024-08-09 21:15:00,2024-09-09 03:15:00,360,43560.0,pole collapse
100,OG-000470,2024-04-07 16:00:00,2024-07-04 17:37:00,97,126817.0,vegetation contact
101,OG-900253,2025-06-12 10:00:00,2025-06-21 13:00:00,180,13140.0,unknown
105,OG-900297,2025-11-01 10:00:00,2025-11-05 13:00:00,180,5940.0,unknown
106,OG-000921,2024-05-10 21:15:00,2024-06-10 00:56:00,221,43421.0,pole collapse
110,OG-900162,2024-10-16 10:00:00,2025-09-18 13:00:00,180,485460.0,unknown
111,OG-900160,2025-12-03 10:00:00,2025-12-11 13:00:00,180,11700.0,unknown
115,OG-002175,2026-03-07 23:00:00,2026-08-03 02:36:00,216,213336.0,cable theft
116,OG-001274,2025-03-05 22:00:00,2025-04-05 01:21:00,201,43401.0,pole collapse
130,OG-002181,2026-09-03 20:00:00,2026-10-03 00:54:00,294,42054.0,pole collapse
137,OG-000378,2024-11-06 15:00:00,2024-06-11 18:11:00,191,-212929.0,vegetation contact
140,OG-900061,2025-03-07 10:00:00,2025-05-10 13:00:00,180,92340.0,unknown
142,OG-000487,2024-08-07 09:30:00,2024-07-08 12:19:00,169,-43031.0,pole collapse
146,OG-900347,2024-07-09 10:00:00,2025-07-17 13:00:00,180,537300.0,unknown
147,OG-002463,2026-06-09 06:00:00,2026-09-06 09:31:00,211,128371.0,vegetation contact
152,OG-900157,2024-12-11 10:00:00,2025-03-04 13:00:00,180,119700.0,unknown
154,OG-900062,2024-11-19 10:00:00,2025-02-18 13:00:00,180,131220.0,unknown
158,OG-001293,2025-08-05 01:00:00,2025-05-08 04:46:00,226,-127934.0,vegetation contact
159,OG-900138,2024-09-12 10:00:00,2025-05-21 13:00:00,180,361620.0,unknown
166,OG-900142,2025-05-07 10:00:00,2025-04-10 13:00:00,180,-38700.0,unknown
168,OG-001073,2025-01-09 08:15:00,2025-09-01 11:19:00,184,338584.0,cable theft
177,OG-000999,2024-11-02 16:45:00,2024-02-11 18:59:00,134,-381466.0,planned maintenance
178,OG-001407,2025-06-10 07:15:00,2025-10-06 08:04:00,49,169969.0,storm damage
191,OG-001092,2025-03-02 20:45:00,2025-02-04 00:01:00,196,-38684.0,lightning strike

In [89]:
before = len(outages_clean)

outages_clean = outages_clean.drop_duplicates().copy()

after = len(outages_clean)

print("Rows before:", before)
print("Rows after:", after)
print("Exact duplicates removed:", before - after)

Rows before: 2891
Rows after: 2891
Exact duplicates removed: 0

In [90]:
duplicate_ids = outages_clean[
    outages_clean["outage_id"].duplicated(keep=False)
]

print("Rows with duplicate outage IDs:", len(duplicate_ids))

Rows with duplicate outage IDs: 0

In [91]:
duplicate_ids.sort_values("outage_id")

Empty DataFrame
Columns: [outage_id, feeder_id, start_ts, end_ts, duration_min, cause, crew_id, customers_affected, calculated_duration_min, duration_difference, duration_mismatch, invalid_time_order, data_quality_issue]
Index: []

In [92]:
project_start = pd.Timestamp("2024-01-01")
project_end = pd.Timestamp("2026-06-30 23:59:59")

outside_period = outages_clean[
    (outages_clean["start_ts"] < project_start) |
    (outages_clean["start_ts"] > project_end) |
    (outages_clean["end_ts"] < project_start) |
    (outages_clean["end_ts"] > project_end)
]

print("Rows outside project period:", len(outside_period))

Rows outside project period: 92

In [93]:
outside_period[
    [
        "outage_id",
        "start_ts",
        "end_ts",
        "duration_min",
        "cause"
    ]
].head(50)

,outage_id,start_ts,end_ts,duration_min,cause
19,OG-002256,2026-04-09 10:00:00,2026-09-04 12:10:00,130,transformer fault
115,OG-002175,2026-03-07 23:00:00,2026-08-03 02:36:00,216,cable theft
119,OG-002267,2026-12-04 04:30:00,2026-12-04 10:48:00,378,pole collapse
130,OG-002181,2026-09-03 20:00:00,2026-10-03 00:54:00,294,pole collapse
147,OG-002463,2026-06-09 06:00:00,2026-09-06 09:31:00,211,vegetation contact
156,OG-002356,2026-09-05 19:15:00,2026-09-05 19:58:00,43,unknown
171,OG-002469,2026-11-06 03:15:00,2026-11-06 06:41:00,206,storm damage
198,OG-002355,2026-09-05 14:30:00,2026-09-05 17:12:00,162,storm damage
237,OG-002119,2026-10-02 16:45:00,2026-02-10 17:59:00,74,lightning strike
276,OG-002263,2026-12-04 21:15:00,2026-04-13 01:23:00,248,lightning strike
283,OG-002118,2026-09-02 14:15:00,2026-09-02 19:59:00,344,equipment failure
303,OG-002353,2026-08-05 06:15:00,2026-08-05 11:17:00,302,vegetation contact
334,OG-002096,2026-12-01 09:15:00,2026-12-01 11:34:00,139,transformer fault
397,OG-002459,2026-08-06 01:00:00,2026-08-06 02:55:00,115,unknown
488,OG-002255,2026-08-04 18:15:00,2026-08-04 21:56:00,221,pole collapse
493,OG-002351,2026-08-05 19:30:00,2026-08-05 22:23:00,173,lightning strike
497,OG-002346,2026-07-05 03:00:00,2026-07-05 04:28:00,88,cable theft
501,OG-002465,2026-10-06 17:00:00,2026-06-10 20:43:00,223,vegetation contact
514,OG-002344,2026-07-05 23:15:00,2026-05-08 02:50:00,215,vegetation contact
518,OG-002180,2026-08-03 09:00:00,2026-08-03 10:23:00,83,lightning strike
548,OG-002188,2026-11-03 22:15:00,2026-12-03 03:20:00,305,storm damage
566,OG-002250,2026-04-07 05:00:00,2026-07-04 09:13:00,253,overload
643,OG-002359,2026-10-05 16:00:00,2026-10-05 17:46:00,106,overload
751,OG-002170,2026-06-03 23:45:00,2026-07-03 02:34:00,169,planned maintenance
785,OG-002362,2026-05-11 20:15:00,2026-11-05 22:01:00,106,vegetation contact
803,OG-002189,2026-11-03 16:45:00,2026-11-03 18:47:00,122,lightning strike
902,OG-002253,2026-04-08 17:30:00,2026-08-04 21:59:00,269,storm damage
904,OG-002121,2026-02-11 20:30:00,2026-11-02 20:38:00,8,vegetation contact
917,OG-002342,2026-07-05 06:30:00,2026-07-05 10:44:00,254,vegetation contact
974,OG-002464,2026-06-10 05:00:00,2026-10-06 08:15:00,195,planned maintenance
1015,OG-002095,2026-07-01 23:30:00,2026-08-01 03:24:00,234,pole collapse
1049,OG-002179,2026-08-03 07:45:00,2026-03-08 11:07:00,202,pole collapse
1061,OG-002462,2026-09-06 16:45:00,2026-09-06 17:25:00,40,equipment failure
1105,OG-002261,2026-10-04 16:15:00,2026-10-04 22:24:00,369,vegetation contact
1123,OG-002185,2026-10-03 13:30:00,2026-10-03 17:07:00,217,vegetation contact
1157,OG-002123,2026-12-02 17:45:00,2026-12-02 17:53:00,8,equipment failure
1183,OG-002343,2026-05-07 21:45:00,2026-07-05 21:53:00,8,pole collapse
1199,OG-002364,2026-12-05 01:45:00,2026-12-05 05:27:00,222,lightning strike
1226,OG-002460,2026-08-06 21:45:00,2026-09-06 01:35:00,230,lightning strike
1282,OG-002248,2026-07-04 05:30:00,2026-04-07 08:26:00,176,planned maintenance
1300,OG-002461,2026-06-09 03:30:00,2026-09-06 05:51:00,141,lightning strike
1305,OG-002260,2026-10-04 13:45:00,2026-10-04 15:55:00,130,storm damage
1311,OG-002466,2026-11-06 03:30:00,2026-11-06 09:49:00,379,lightning strike
1323,OG-002098,2026-01-12 04:00:00,2026-12-01 05:20:00,80,planned maintenance
1338,OG-002473,2026-06-12 17:15:00,2026-12-06 23:01:00,346,lightning strike
1357,OG-002257,2026-10-04 21:00:00,2026-10-04 23:24:00,144,transformer fault
1426,OG-002476,2026-12-06 22:00:00,2026-12-06 23:32:00,92,storm damage
1484,OG-002475,2026-06-12 02:30:00,2026-12-06 04:08:00,98,pole collapse
1488,OG-002251,2026-07-04 10:30:00,2026-07-04 15:02:00,272,storm damage
1490,OG-002187,2026-11-03 06:30:00,2026-03-11 08:51:00,141,lightning strike

In [94]:
valid_feeders = set(feeders["feeder_id"].dropna())

invalid_feeder_rows = outages_clean[
    ~outages_clean["feeder_id"].isin(valid_feeders)
]

print("Invalid feeder rows:", len(invalid_feeder_rows))

Invalid feeder rows: 350

In [95]:
invalid_feeder_rows[
    [
        "outage_id",
        "feeder_id",
        "start_ts",
        "end_ts",
        "duration_min",
        "cause"
    ]
].sort_values("feeder_id")

,outage_id,feeder_id,start_ts,end_ts,duration_min,cause
1753,OG-900000,FD-900,2024-10-19 10:00:00,2025-10-03 13:00:00,180,unknown
1431,OG-900001,FD-901,2024-06-03 10:00:00,2025-06-28 13:00:00,180,unknown
1152,OG-900002,FD-902,2025-04-26 10:00:00,2025-06-21 13:00:00,180,unknown
1851,OG-900003,FD-903,2024-04-13 10:00:00,2025-10-26 13:00:00,180,unknown
540,OG-900004,FD-904,2024-05-05 10:00:00,2025-12-08 13:00:00,180,unknown
...,...,...,...,...,...,...
2508,OG-900095,FD-995,2025-07-22 10:00:00,2025-10-03 13:00:00,180,unknown
1256,OG-900096,FD-996,2024-09-08 10:00:00,2025-12-12 13:00:00,180,unknown
2974,OG-900097,FD-997,2025-07-23 10:00:00,2025-04-10 13:00:00,180,unknown
2131,OG-900098,FD-998,2025-08-22 10:00:00,2025-12-13 13:00:00,180,unknown
1556,OG-900099,FD-999,2025-12-02 10:00:00,2025-02-12 13:00:00,180,unknown

In [96]:
print(meters["installed_on"].head(10))

0   2023-08-26
1          NaT
2   2020-02-07
3          NaT
4          NaT
5          NaT
6          NaT
7          NaT
8          NaT
9          NaT
Name: installed_on, dtype: datetime64[us]

In [97]:
invalid_feeder_ids = sorted(
    invalid_feeder_rows["feeder_id"].dropna().unique()
)

print(invalid_feeder_ids)

['FD-900', 'FD-901', 'FD-902', 'FD-903', 'FD-904', 'FD-905', 'FD-906', 'FD-907', 'FD-908', 'FD-909', 'FD-910', 'FD-9100', 'FD-9101', 'FD-9102', 'FD-9103', 'FD-9104', 'FD-9105', 'FD-9106', 'FD-9107', 'FD-9108', 'FD-9109', 'FD-911', 'FD-9110', 'FD-9111', 'FD-9112', 'FD-9113', 'FD-9114', 'FD-9115', 'FD-9116', 'FD-9117', 'FD-9118', 'FD-9119', 'FD-912', 'FD-9120', 'FD-9121', 'FD-9122', 'FD-9123', 'FD-9124', 'FD-9125', 'FD-9126', 'FD-9127', 'FD-9128', 'FD-9129', 'FD-913', 'FD-9130', 'FD-9131', 'FD-9132', 'FD-9133', 'FD-9134', 'FD-9135', 'FD-9136', 'FD-9137', 'FD-9138', 'FD-9139', 'FD-914', 'FD-9140', 'FD-9141', 'FD-9142', 'FD-9143', 'FD-9144', 'FD-9145', 'FD-9146', 'FD-9147', 'FD-9148', 'FD-9149', 'FD-915', 'FD-9150', 'FD-9151', 'FD-9152', 'FD-9153', 'FD-9154', 'FD-9155', 'FD-9156', 'FD-9157', 'FD-9158', 'FD-9159', 'FD-916', 'FD-9160', 'FD-9161', 'FD-9162', 'FD-9163', 'FD-9164', 'FD-9165', 'FD-9166', 'FD-9167', 'FD-9168', 'FD-9169', 'FD-917', 'FD-9170', 'FD-9171', 'FD-9172', 'FD-9173', 'FD-9174', 'FD-9175', 'FD-9176', 'FD-9177', 'FD-9178', 'FD-9179', 'FD-918', 'FD-9180', 'FD-9181', 'FD-9182', 'FD-9183', 'FD-9184', 'FD-9185', 'FD-9186', 'FD-9187', 'FD-9188', 'FD-9189', 'FD-919', 'FD-9190', 'FD-9191', 'FD-9192', 'FD-9193', 'FD-9194', 'FD-9195', 'FD-9196', 'FD-9197', 'FD-9198', 'FD-9199', 'FD-920', 'FD-9200', 'FD-9201', 'FD-9202', 'FD-9203', 'FD-9204', 'FD-9205', 'FD-9206', 'FD-9207', 'FD-9208', 'FD-9209', 'FD-921', 'FD-9210', 'FD-9211', 'FD-9212', 'FD-9213', 'FD-9214', 'FD-9215', 'FD-9216', 'FD-9217', 'FD-9218', 'FD-9219', 'FD-922', 'FD-9220', 'FD-9221', 'FD-9222', 'FD-9223', 'FD-9224', 'FD-9225', 'FD-9226', 'FD-9227', 'FD-9228', 'FD-9229', 'FD-923', 'FD-9230', 'FD-9231', 'FD-9232', 'FD-9233', 'FD-9234', 'FD-9235', 'FD-9236', 'FD-9237', 'FD-9238', 'FD-9239', 'FD-924', 'FD-9240', 'FD-9241', 'FD-9242', 'FD-9243', 'FD-9244', 'FD-9245', 'FD-9246', 'FD-9247', 'FD-9248', 'FD-9249', 'FD-925', 'FD-9250', 'FD-9251', 'FD-9252', 'FD-9253', 'FD-9254', 'FD-9255', 'FD-9256', 'FD-9257', 'FD-9258', 'FD-9259', 'FD-926', 'FD-9260', 'FD-9261', 'FD-9262', 'FD-9263', 'FD-9264', 'FD-9265', 'FD-9266', 'FD-9267', 'FD-9268', 'FD-9269', 'FD-927', 'FD-9270', 'FD-9271', 'FD-9272', 'FD-9273', 'FD-9274', 'FD-9275', 'FD-9276', 'FD-9277', 'FD-9278', 'FD-9279', 'FD-928', 'FD-9280', 'FD-9281', 'FD-9282', 'FD-9283', 'FD-9284', 'FD-9285', 'FD-9286', 'FD-9287', 'FD-9288', 'FD-9289', 'FD-929', 'FD-9290', 'FD-9291', 'FD-9292', 'FD-9293', 'FD-9294', 'FD-9295', 'FD-9296', 'FD-9297', 'FD-9298', 'FD-9299', 'FD-930', 'FD-9300', 'FD-9301', 'FD-9302', 'FD-9303', 'FD-9304', 'FD-9305', 'FD-9306', 'FD-9307', 'FD-9308', 'FD-9309', 'FD-931', 'FD-9310', 'FD-9311', 'FD-9312', 'FD-9313', 'FD-9314', 'FD-9315', 'FD-9316', 'FD-9317', 'FD-9318', 'FD-9319', 'FD-932', 'FD-9320', 'FD-9321', 'FD-9322', 'FD-9323', 'FD-9324', 'FD-9325', 'FD-9326', 'FD-9327', 'FD-9328', 'FD-9329', 'FD-933', 'FD-9330', 'FD-9331', 'FD-9332', 'FD-9333', 'FD-9334', 'FD-9335', 'FD-9336', 'FD-9337', 'FD-9338', 'FD-9339', 'FD-934', 'FD-9340', 'FD-9341', 'FD-9342', 'FD-9343', 'FD-9344', 'FD-9345', 'FD-9346', 'FD-9347', 'FD-9348', 'FD-9349', 'FD-935', 'FD-936', 'FD-937', 'FD-938', 'FD-939', 'FD-940', 'FD-941', 'FD-942', 'FD-943', 'FD-944', 'FD-945', 'FD-946', 'FD-947', 'FD-948', 'FD-949', 'FD-950', 'FD-951', 'FD-952', 'FD-953', 'FD-954', 'FD-955', 'FD-956', 'FD-957', 'FD-958', 'FD-959', 'FD-960', 'FD-961', 'FD-962', 'FD-963', 'FD-964', 'FD-965', 'FD-966', 'FD-967', 'FD-968', 'FD-969', 'FD-970', 'FD-971', 'FD-972', 'FD-973', 'FD-974', 'FD-975', 'FD-976', 'FD-977', 'FD-978', 'FD-979', 'FD-980', 'FD-981', 'FD-982', 'FD-983', 'FD-984', 'FD-985', 'FD-986', 'FD-987', 'FD-988', 'FD-989', 'FD-990', 'FD-991', 'FD-992', 'FD-993', 'FD-994', 'FD-995', 'FD-996', 'FD-997', 'FD-998', 'FD-999']

In [98]:
invalid_feeder_format = outages_clean[
    ~outages_clean["feeder_id"].str.match(
        r"^FD-\d{3}$",
        na=False
    )
]

print("Invalid feeder ID format:", len(invalid_feeder_format))

Invalid feeder ID format: 250

In [99]:
invalid_feeder_format[
    ["outage_id", "feeder_id"]
].head(50)

     outage_id feeder_id
10   OG-900288   FD-9288
24   OG-900333   FD-9333
49   OG-900313   FD-9313
75   OG-900334   FD-9334
86   OG-900211   FD-9211
94   OG-900312   FD-9312
101  OG-900253   FD-9253
105  OG-900297   FD-9297
110  OG-900162   FD-9162
111  OG-900160   FD-9160
146  OG-900347   FD-9347
152  OG-900157   FD-9157
159  OG-900138   FD-9138
166  OG-900142   FD-9142
208  OG-900278   FD-9278
224  OG-900234   FD-9234
244  OG-900336   FD-9336
257  OG-900104   FD-9104
266  OG-900265   FD-9265
268  OG-900123   FD-9123
271  OG-900261   FD-9261
281  OG-900309   FD-9309
282  OG-900286   FD-9286
284  OG-900338   FD-9338
288  OG-900290   FD-9290
324  OG-900196   FD-9196
332  OG-900155   FD-9155
336  OG-900220   FD-9220
360  OG-900263   FD-9263
375  OG-900151   FD-9151
377  OG-900127   FD-9127
389  OG-900260   FD-9260
399  OG-900270   FD-9270
411  OG-900282   FD-9282
418  OG-900167   FD-9167
430  OG-900141   FD-9141
432  OG-900285   FD-9285
434  OG-900102   FD-9102
449  OG-900152   FD-9152
456  OG-900108   FD-9108
457  OG-900273   FD-9273
485  OG-900303   FD-9303
507  OG-900219   FD-9219
513  OG-900233   FD-9233
515  OG-900315   FD-9315
528  OG-900230   FD-9230
538  OG-900239   FD-9239
549  OG-900165   FD-9165
552  OG-900324   FD-9324
555  OG-900221   FD-9221

In [100]:
invalid_feeder_format["feeder_id"].value_counts(dropna=False)

feeder_id
FD-9288    1
FD-9333    1
FD-9313    1
FD-9334    1
FD-9211    1
          ..
FD-9149    1
FD-9335    1
FD-9280    1
FD-9180    1
FD-9318    1
Name: count, Length: 250, dtype: int64

In [101]:
project_start = pd.Timestamp("2024-01-01")
project_end = pd.Timestamp("2026-06-30 23:59:59")

bad_timestamp_records = (
    outages_clean["start_ts"].isna()
    | outages_clean["end_ts"].isna()
    | (outages_clean["end_ts"] < outages_clean["start_ts"])
    | (outages_clean["duration_difference"].abs() > 1)
    | (outages_clean["start_ts"] < project_start)
    | (outages_clean["start_ts"] > project_end)
    | (outages_clean["end_ts"] < project_start)
    | (outages_clean["end_ts"] > project_end)
)

In [102]:
outages_quarantine = outages_clean[bad_timestamp_records].copy()

print("Quarantined records:", len(outages_quarantine))

Quarantined records: 829

In [103]:
outages_clean = outages_clean[~bad_timestamp_records].copy()

print("Remaining clean rows:", len(outages_clean))

Remaining clean rows: 2062

In [104]:
print("Remaining timestamp problems:")

print(
    (
        outages_clean["start_ts"].isna()
        | outages_clean["end_ts"].isna()
        | (outages_clean["end_ts"] < outages_clean["start_ts"])
        | (outages_clean["duration_difference"].abs() > 1)
    ).sum()
)

Remaining timestamp problems:
0

In [105]:
invalid_feeder_mask = ~outages_clean["feeder_id"].isin(valid_feeder_ids)

outages_feeder_quarantine = outages_clean[
    invalid_feeder_mask
].copy()

print("Invalid-feeder records:", len(outages_feeder_quarantine))

Invalid-feeder records: 1

In [106]:
outages_clean = outages_clean[
    ~invalid_feeder_mask
].copy()

print("Clean outage rows:", len(outages_clean))

Clean outage rows: 2061

In [107]:
invalid_feeder_mask = ~outages_clean["feeder_id"].isin(valid_feeder_ids)

outages_feeder_quarantine = outages_clean[
    invalid_feeder_mask
].copy()

outages_clean = outages_clean[
    ~invalid_feeder_mask
].copy()

print("Moved to feeder quarantine:", len(outages_feeder_quarantine))
print("Remaining clean rows:", len(outages_clean))

Moved to feeder quarantine: 0
Remaining clean rows: 2061

In [108]:
outages_clean[
    ~outages_clean["feeder_id"].isin(valid_feeder_ids)
].shape

(0, 13)

In [109]:
helper_columns = [
    "calculated_duration_min",
    "duration_difference",
    "duration_mismatch",
    "invalid_time_order",
    "data_quality_issue"
]

outages_clean = outages_clean.drop(
    columns=helper_columns,
    errors="ignore"
)

In [110]:
outages_clean.columns.tolist()

['outage_id',
 'feeder_id',
 'start_ts',
 'end_ts',
 'duration_min',
 'cause',
 'crew_id',
 'customers_affected']

In [111]:
outages_clean.dtypes

outage_id                        str
feeder_id                        str
start_ts              datetime64[us]
end_ts                datetime64[us]
duration_min                   int64
cause                            str
crew_id                          str
customers_affected             int64
dtype: object

In [112]:
outages_clean.isna().sum()

outage_id               0
feeder_id               0
start_ts                0
end_ts                  0
duration_min            0
cause                   0
crew_id               113
customers_affected      0
dtype: int64

In [113]:
print("Final cleaned rows:", len(outages_clean))
print("Final columns:", len(outages_clean.columns))

Final cleaned rows: 2061
Final columns: 8

In [114]:
outages_clean.head()

,outage_id,feeder_id,start_ts,end_ts,duration_min,cause,crew_id,customers_affected
0,OG-001652,FD-024,2025-10-08 19:15:00,2025-10-08 20:59:00,104,lightning strike,CR-13,1270
1,OG-000355,FD-005,2024-05-06 19:45:00,2024-05-06 21:48:00,123,lightning strike,CR-07,3255
2,OG-002224,FD-020,2026-03-31 05:30:00,2026-03-31 07:49:00,139,storm damage,CR-14,2227
4,OG-000587,FD-010,2024-01-08 15:15:00,2024-01-08 16:51:00,96,storm damage,CR-03,61
5,OG-001511,FD-030,2025-10-07 14:15:00,2025-10-07 16:45:00,150,storm damage,CR-10,7841

In [115]:
outages_clean.info()

<class 'pandas.DataFrame'>
Index: 2061 entries, 0 to 3020
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   outage_id           2061 non-null   str
 1   feeder_id           2061 non-null   str
 2   start_ts            2061 non-null   datetime64[us]
 3   end_ts              2061 non-null   datetime64[us]
 4   duration_min        2061 non-null   int64
 5   cause               2061 non-null   str
 6   crew_id             1948 non-null   str
 7   customers_affected  2061 non-null   int64
dtypes: datetime64[us](2), int64(2), str(4)
memory usage: 144.9 KB

In [116]:
outages_clean.to_csv(
    "outages_clean.csv",
    index=False
)

In [117]:
outages_clean.to_csv(
    "outages_clean.csv",
    index=False
)

In [118]:
cleaned_check = pd.read_csv(
    "outages_clean.csv",
    parse_dates=["start_ts", "end_ts"]
)

print(cleaned_check.shape)
print(cleaned_check.isna().sum())
print(cleaned_check.head())

(2061, 8)
outage_id               0
feeder_id               0
start_ts                0
end_ts                  0
duration_min            0
cause                   0
crew_id               113
customers_affected      0
dtype: int64
   outage_id feeder_id            start_ts              end_ts  duration_min  \
0  OG-001652    FD-024 2025-10-08 19:15:00 2025-10-08 20:59:00           104
1  OG-000355    FD-005 2024-05-06 19:45:00 2024-05-06 21:48:00           123
2  OG-002224    FD-020 2026-03-31 05:30:00 2026-03-31 07:49:00           139
3  OG-000587    FD-010 2024-01-08 15:15:00 2024-01-08 16:51:00            96
4  OG-001511    FD-030 2025-10-07 14:15:00 2025-10-07 16:45:00           150

              cause crew_id  customers_affected
0  lightning strike   CR-13                1270
1  lightning strike   CR-07                3255
2      storm damage   CR-14                2227
3      storm damage   CR-03                  61
4      storm damage   CR-10                7841

In [119]:
print("RAW ROWS:", len(outages))
print("CLEAN ROWS:", len(outages_clean))
print("QUARANTINED TIMESTAMP/DATE ROWS:", len(outages_quarantine))
print("QUARANTINED INVALID-FEEDER ROWS:", len(outages_feeder_quarantine))
print("MISSING CREW IDS:", outages_clean["crew_id"].isna().sum())

RAW ROWS: 3021
CLEAN ROWS: 2061
QUARANTINED TIMESTAMP/DATE ROWS: 829
QUARANTINED INVALID-FEEDER ROWS: 0
MISSING CREW IDS: 113

In [120]:
cleaning_summary = {
    "raw_rows": len(outages),
    "clean_rows": len(outages_clean),
    "timestamp_quarantine_rows": len(outages_quarantine),
    "invalid_feeder_rows": len(outages_feeder_quarantine),
    "missing_crew_ids": int(outages_clean["crew_id"].isna().sum()),
}

cleaning_summary

{'raw_rows': 3021,
 'clean_rows': 2061,
 'timestamp_quarantine_rows': 829,
 'invalid_feeder_rows': 0,
 'missing_crew_ids': 113}

In [121]:
feeders[
    [
        "feeder_id",
        "latitude",
        "longitude"
    ]
].head()

  feeder_id  latitude  longitude
0    FD-001   5.96021   10.16141
1    FD-002   5.95957   10.14537
2    FD-003   5.96261   10.11069
3    FD-004   5.97457   10.14588
4    FD-005   6.02148   10.18291

In [122]:
print("Number of feeders:", len(feeders))
print("Missing latitude:", feeders["latitude"].isna().sum())
print("Missing longitude:", feeders["longitude"].isna().sum())

Number of feeders: 37
Missing latitude: 0
Missing longitude: 0

In [123]:
feeders[
    ["latitude", "longitude"]
].drop_duplicates().shape

(37, 2)

In [124]:
print("Total feeders:", len(feeders))

Total feeders: 37

In [125]:
unique_coordinates = (
    feeders[["latitude", "longitude"]]
    .drop_duplicates()
)

print("Unique coordinate pairs:", len(unique_coordinates))

Unique coordinate pairs: 37

In [126]:
unique_coordinates

    latitude  longitude
0    5.96021   10.16141
1    5.95957   10.14537
2    5.96261   10.11069
3    5.97457   10.14588
4    6.02148   10.18291
5    5.95909   10.10838
6    5.96298   10.15734
7    5.97171   10.13234
8    5.95671   10.13663
9    6.11700   10.13130
10   6.06413   10.08947
11   6.10025   10.09759
12   5.87102   10.03345
13   5.88578   10.05373
14   5.89666   10.02107
15   5.81294   10.23152
16   5.81553   10.18174
17   5.81764   10.18719
18   5.96008   10.44812
19   5.97999   10.47763
20   5.98039   10.42040
21   5.97303   10.41656
22   6.17975   10.64770
23   6.22260   10.65005
24   6.21059   10.64215
25   6.39978   10.06622
26   6.37787   10.05152
27   6.40935   10.06738
28   6.38871   10.04671
29   6.25306   10.30449
30   6.25346   10.26216
31   6.24561   10.25013
32   5.97679   10.00766
33   6.00523   10.02378
34   5.80107    9.85587
35   5.84332    9.85139
36   5.83648    9.85903

In [127]:
coordinate_groups = (
    feeders
    .groupby(["latitude", "longitude"])["feeder_id"]
    .apply(list)
    .reset_index(name="feeder_ids")
)

coordinate_groups

    latitude  longitude feeder_ids
0    5.80107    9.85587   [FD-035]
1    5.81294   10.23152   [FD-016]
2    5.81553   10.18174   [FD-017]
3    5.81764   10.18719   [FD-018]
4    5.83648    9.85903   [FD-037]
5    5.84332    9.85139   [FD-036]
6    5.87102   10.03345   [FD-013]
7    5.88578   10.05373   [FD-014]
8    5.89666   10.02107   [FD-015]
9    5.95671   10.13663   [FD-009]
10   5.95909   10.10838   [FD-006]
11   5.95957   10.14537   [FD-002]
12   5.96008   10.44812   [FD-019]
13   5.96021   10.16141   [FD-001]
14   5.96261   10.11069   [FD-003]
15   5.96298   10.15734   [FD-007]
16   5.97171   10.13234   [FD-008]
17   5.97303   10.41656   [FD-022]
18   5.97457   10.14588   [FD-004]
19   5.97679   10.00766   [FD-033]
20   5.97999   10.47763   [FD-020]
21   5.98039   10.42040   [FD-021]
22   6.00523   10.02378   [FD-034]
23   6.02148   10.18291   [FD-005]
24   6.06413   10.08947   [FD-011]
25   6.10025   10.09759   [FD-012]
26   6.11700   10.13130   [FD-010]
27   6.17975   10.64770   [FD-023]
28   6.21059   10.64215   [FD-025]
29   6.22260   10.65005   [FD-024]
30   6.24561   10.25013   [FD-032]
31   6.25306   10.30449   [FD-030]
32   6.25346   10.26216   [FD-031]
33   6.37787   10.05152   [FD-027]
34   6.38871   10.04671   [FD-029]
35   6.39978   10.06622   [FD-026]
36   6.40935   10.06738   [FD-028]

In [128]:
print("Total feeders:", len(feeders))

unique_coordinates = (
    feeders[["latitude", "longitude"]]
    .drop_duplicates()
)

print("Unique coordinate pairs:", len(unique_coordinates))

Total feeders: 37
Unique coordinate pairs: 37

In [129]:
unique_coordinates

    latitude  longitude
0    5.96021   10.16141
1    5.95957   10.14537
2    5.96261   10.11069
3    5.97457   10.14588
4    6.02148   10.18291
5    5.95909   10.10838
6    5.96298   10.15734
7    5.97171   10.13234
8    5.95671   10.13663
9    6.11700   10.13130
10   6.06413   10.08947
11   6.10025   10.09759
12   5.87102   10.03345
13   5.88578   10.05373
14   5.89666   10.02107
15   5.81294   10.23152
16   5.81553   10.18174
17   5.81764   10.18719
18   5.96008   10.44812
19   5.97999   10.47763
20   5.98039   10.42040
21   5.97303   10.41656
22   6.17975   10.64770
23   6.22260   10.65005
24   6.21059   10.64215
25   6.39978   10.06622
26   6.37787   10.05152
27   6.40935   10.06738
28   6.38871   10.04671
29   6.25306   10.30449
30   6.25346   10.26216
31   6.24561   10.25013
32   5.97679   10.00766
33   6.00523   10.02378
34   5.80107    9.85587
35   5.84332    9.85139
36   5.83648    9.85903

In [130]:
coordinate_groups = (
    feeders
    .groupby(["latitude", "longitude"])["feeder_id"]
    .apply(list)
    .reset_index(name="feeder_ids")
)

coordinate_groups

    latitude  longitude feeder_ids
0    5.80107    9.85587   [FD-035]
1    5.81294   10.23152   [FD-016]
2    5.81553   10.18174   [FD-017]
3    5.81764   10.18719   [FD-018]
4    5.83648    9.85903   [FD-037]
5    5.84332    9.85139   [FD-036]
6    5.87102   10.03345   [FD-013]
7    5.88578   10.05373   [FD-014]
8    5.89666   10.02107   [FD-015]
9    5.95671   10.13663   [FD-009]
10   5.95909   10.10838   [FD-006]
11   5.95957   10.14537   [FD-002]
12   5.96008   10.44812   [FD-019]
13   5.96021   10.16141   [FD-001]
14   5.96261   10.11069   [FD-003]
15   5.96298   10.15734   [FD-007]
16   5.97171   10.13234   [FD-008]
17   5.97303   10.41656   [FD-022]
18   5.97457   10.14588   [FD-004]
19   5.97679   10.00766   [FD-033]
20   5.97999   10.47763   [FD-020]
21   5.98039   10.42040   [FD-021]
22   6.00523   10.02378   [FD-034]
23   6.02148   10.18291   [FD-005]
24   6.06413   10.08947   [FD-011]
25   6.10025   10.09759   [FD-012]
26   6.11700   10.13130   [FD-010]
27   6.17975   10.64770   [FD-023]
28   6.21059   10.64215   [FD-025]
29   6.22260   10.65005   [FD-024]
30   6.24561   10.25013   [FD-032]
31   6.25306   10.30449   [FD-030]
32   6.25346   10.26216   [FD-031]
33   6.37787   10.05152   [FD-027]
34   6.38871   10.04671   [FD-029]
35   6.39978   10.06622   [FD-026]
36   6.40935   10.06738   [FD-028]

In [131]:
print(meters["installed_on"].head(10))

0   2023-08-26
1          NaT
2   2020-02-07
3          NaT
4          NaT
5          NaT
6          NaT
7          NaT
8          NaT
9          NaT
Name: installed_on, dtype: datetime64[us]

In [132]:
print("Total feeders:", len(feeders))
print("Unique coordinate pairs:", len(unique_coordinates))

Total feeders: 37
Unique coordinate pairs: 37

In [133]:
print(coordinate_groups[["latitude", "longitude", "feeder_ids"]])

    latitude  longitude feeder_ids
0    5.80107    9.85587   [FD-035]
1    5.81294   10.23152   [FD-016]
2    5.81553   10.18174   [FD-017]
3    5.81764   10.18719   [FD-018]
4    5.83648    9.85903   [FD-037]
5    5.84332    9.85139   [FD-036]
6    5.87102   10.03345   [FD-013]
7    5.88578   10.05373   [FD-014]
8    5.89666   10.02107   [FD-015]
9    5.95671   10.13663   [FD-009]
10   5.95909   10.10838   [FD-006]
11   5.95957   10.14537   [FD-002]
12   5.96008   10.44812   [FD-019]
13   5.96021   10.16141   [FD-001]
14   5.96261   10.11069   [FD-003]
15   5.96298   10.15734   [FD-007]
16   5.97171   10.13234   [FD-008]
17   5.97303   10.41656   [FD-022]
18   5.97457   10.14588   [FD-004]
19   5.97679   10.00766   [FD-033]
20   5.97999   10.47763   [FD-020]
21   5.98039   10.42040   [FD-021]
22   6.00523   10.02378   [FD-034]
23   6.02148   10.18291   [FD-005]
24   6.06413   10.08947   [FD-011]
25   6.10025   10.09759   [FD-012]
26   6.11700   10.13130   [FD-010]
27   6.17975   10.64770   [FD-023]
28   6.21059   10.64215   [FD-025]
29   6.22260   10.65005   [FD-024]
30   6.24561   10.25013   [FD-032]
31   6.25306   10.30449   [FD-030]
32   6.25346   10.26216   [FD-031]
33   6.37787   10.05152   [FD-027]
34   6.38871   10.04671   [FD-029]
35   6.39978   10.06622   [FD-026]
36   6.40935   10.06738   [FD-028]

In [134]:
print(meters["installed_on"].head(10))

0   2023-08-26
1          NaT
2   2020-02-07
3          NaT
4          NaT
5          NaT
6          NaT
7          NaT
8          NaT
9          NaT
Name: installed_on, dtype: datetime64[us]

In [135]:
print("Total feeders:", len(feeders))

unique_coordinates = (
    feeders[["latitude", "longitude"]]
    .drop_duplicates()
)

print("Unique coordinate pairs:", len(unique_coordinates))

Total feeders: 37
Unique coordinate pairs: 37

In [136]:
print("Earliest outage date:", outages["start_ts"].min())
print("Latest outage date:", outages["start_ts"].max())

Earliest outage date: 2024-01-02 08:15:00
Latest outage date: 2026-12-06 22:00:00

In [137]:
outages[["start_ts", "end_ts"]].head()

             start_ts              end_ts
0 2025-10-08 19:15:00 2025-10-08 20:59:00
1 2024-05-06 19:45:00 2024-05-06 21:48:00
2 2026-03-31 05:30:00 2026-03-31 07:49:00
3 2025-04-08 17:30:00 2025-08-04 20:19:00
4 2024-01-08 15:15:00 2024-01-08 16:51:00

In [138]:
print("Earliest outage:", outages["start_ts"].min())
print("Latest outage:", outages["start_ts"].max())

Earliest outage: 2024-01-02 08:15:00
Latest outage: 2026-12-06 22:00:00

In [139]:
print(outages["start_ts"].dtype)
print(outages["end_ts"].dtype)

datetime64[us]
datetime64[us]

In [140]:
coordinate_groups = (
    feeders
    .groupby(["latitude", "longitude"])["feeder_id"]
    .apply(list)
    .reset_index(name="feeder_ids")
)

coordinate_groups

    latitude  longitude feeder_ids
0    5.80107    9.85587   [FD-035]
1    5.81294   10.23152   [FD-016]
2    5.81553   10.18174   [FD-017]
3    5.81764   10.18719   [FD-018]
4    5.83648    9.85903   [FD-037]
5    5.84332    9.85139   [FD-036]
6    5.87102   10.03345   [FD-013]
7    5.88578   10.05373   [FD-014]
8    5.89666   10.02107   [FD-015]
9    5.95671   10.13663   [FD-009]
10   5.95909   10.10838   [FD-006]
11   5.95957   10.14537   [FD-002]
12   5.96008   10.44812   [FD-019]
13   5.96021   10.16141   [FD-001]
14   5.96261   10.11069   [FD-003]
15   5.96298   10.15734   [FD-007]
16   5.97171   10.13234   [FD-008]
17   5.97303   10.41656   [FD-022]
18   5.97457   10.14588   [FD-004]
19   5.97679   10.00766   [FD-033]
20   5.97999   10.47763   [FD-020]
21   5.98039   10.42040   [FD-021]
22   6.00523   10.02378   [FD-034]
23   6.02148   10.18291   [FD-005]
24   6.06413   10.08947   [FD-011]
25   6.10025   10.09759   [FD-012]
26   6.11700   10.13130   [FD-010]
27   6.17975   10.64770   [FD-023]
28   6.21059   10.64215   [FD-025]
29   6.22260   10.65005   [FD-024]
30   6.24561   10.25013   [FD-032]
31   6.25306   10.30449   [FD-030]
32   6.25346   10.26216   [FD-031]
33   6.37787   10.05152   [FD-027]
34   6.38871   10.04671   [FD-029]
35   6.39978   10.06622   [FD-026]
36   6.40935   10.06738   [FD-028]

In [141]:
print("Total feeders:", len(feeders))

unique_coordinates = (
    feeders[["latitude", "longitude"]]
    .drop_duplicates()
)

print("Unique coordinate pairs:", len(unique_coordinates))

Total feeders: 37
Unique coordinate pairs: 37

In [142]:
unique_coordinates

    latitude  longitude
0    5.96021   10.16141
1    5.95957   10.14537
2    5.96261   10.11069
3    5.97457   10.14588
4    6.02148   10.18291
5    5.95909   10.10838
6    5.96298   10.15734
7    5.97171   10.13234
8    5.95671   10.13663
9    6.11700   10.13130
10   6.06413   10.08947
11   6.10025   10.09759
12   5.87102   10.03345
13   5.88578   10.05373
14   5.89666   10.02107
15   5.81294   10.23152
16   5.81553   10.18174
17   5.81764   10.18719
18   5.96008   10.44812
19   5.97999   10.47763
20   5.98039   10.42040
21   5.97303   10.41656
22   6.17975   10.64770
23   6.22260   10.65005
24   6.21059   10.64215
25   6.39978   10.06622
26   6.37787   10.05152
27   6.40935   10.06738
28   6.38871   10.04671
29   6.25306   10.30449
30   6.25346   10.26216
31   6.24561   10.25013
32   5.97679   10.00766
33   6.00523   10.02378
34   5.80107    9.85587
35   5.84332    9.85139
36   5.83648    9.85903

In [143]:
print("Total feeders:", len(feeders))

unique_coordinates = (
    feeders[["latitude", "longitude"]]
    .drop_duplicates()
)

print("Unique coordinate pairs:", len(unique_coordinates))

Total feeders: 37
Unique coordinate pairs: 37

In [144]:
cleaned_feeders.to_csv("../data/cleaned_feeders.csv", index=False)

NameError: name 'cleaned_feeders' is not defined